#!/usr/bin/env python3
"""Enforce the Open Horizons fleet task contract at Copilot hook boundaries.

Phase 0 `CONFINED_LITE`. Command tools are removed from fleet subagents rather
than inspected, the control plane lives outside the repository and is sealed
with a launcher key, and every verdict input is content-addressed. The
regular-expression tripwire is retained for evidence only; it is not a
security boundary.
"""

from __future__ import annotations

# Importing a sibling module must not leave `__pycache__` inside the hook
# surface; the repository treats generated bytecode there as residue.
import sys

sys.dont_write_bytecode = True

import json  # noqa: E402
import os  # noqa: E402
import re  # noqa: E402
import subprocess  # noqa: E402
import time  # noqa: E402
import uuid  # noqa: E402
from contextlib import contextmanager  # noqa: E402
from datetime import UTC, datetime  # noqa: E402
from pathlib import Path  # noqa: E402
from typing import Any, Iterator  # noqa: E402

sys.path.insert(0, str(Path(__file__).resolve().parent))

import fleet_policy  # noqa: E402
import fleet_sandbox  # noqa: E402
from fleet_policy import PolicyError, SealError  # noqa: E402


# The deadline for bounded work starts when the process starts, not when the
# validation function is entered, so pre-validation git work is inside it.
PROCESS_START = time.monotonic()

CONTRACT_ENV = fleet_policy.CONTRACT_ENV
COPILOT_RUNAWAY_BLOCK_GUARD = fleet_policy.COPILOT_RUNAWAY_BLOCK_GUARD
VALIDATION_GATE_DESCRIPTOR = Path(".github") / "hooks" / "30-validation-gate.json"

WORKER_RESULT = re.compile(
    r"^FLEET_RESULT:\s*(T\d{3}-\d{3}):\s*(PASS|FAIL|BLOCKED)\s*$",
    re.MULTILINE,
)
VALIDATOR_RESULT = re.compile(
    r"^FLEET_VALIDATION:\s*(T\d{3}-\d{3}):\s*(PASS|FAIL)\s*$",
    re.MULTILINE,
)
COMMAND_KEYS = {"cmd", "command", "script"}
AGENT_KEYS = (
    "agent",
    "agentName",
    "agent_name",
    "agentType",
    "agent_type",
    "subagent_type",
    "subagentType",
    "name",
)
# Claude-format `PreToolUse` payloads report Claude tool names rather than
# runtime names (hooks reference, "Claude-format matchers").
CLAUDE_TOOL_ALIASES = {
    "agent": "task",
    "askuserquestion": "ask_user",
    "bash": "bash",
    "edit": "edit",
    "glob": "glob",
    "grep": "grep",
    "multiedit": "edit",
    "notebookedit": "notebook_edit",
    "notebookread": "view",
    "read": "view",
    "task": "task",
    "todowrite": "update_todo",
    "webfetch": "web_fetch",
    "websearch": "web_search",
    "write": "create",
}
PATH_KEYS = {
    "file",
    "file_path",
    "filepath",
    "filename",
    "notebook_path",
    "path",
    "target_path",
}
PATCH_KEYS = {"input", "patch", "patch_text"}
# Tools whose only relationship to a path is reading it. Everything *else* that
# exposes a `PATH_KEYS`/`PATCH_KEYS` destination is ownership-checked regardless
# of its name, mirroring the command side's fail-closed argument-shape rule
# (finding N8).
READ_ONLY_PATH_TOOLS = frozenset(
    {
        "file_search",
        "glob",
        "grep",
        "list_dir",
        "ls",
        "read",
        "read_file",
        "rg",
        "search",
        "view",
    }
)
# Payload keys that may carry the runtime's own dispatch correlation id.
DISPATCH_ID_KEYS = (
    "dispatchId",
    "dispatch_id",
    "subagentId",
    "subagent_id",
    "invocationId",
    "invocation_id",
    "toolCallId",
    "tool_call_id",
)
# Documented hook payload fields that are runtime metadata rather than tool
# arguments (hooks reference, per-event payload shapes), plus the correlation
# ids the gate itself reads. When a payload carries no recognized argument
# container, everything *outside* this set is still swept for path- and
# command-shaped values, so an undocumented container such as `arguments`
# cannot smuggle a destination past the ownership and control-plane checks.
# Only documented scalar metadata is listed: excluding a key also stops the
# sweep from descending into it, so an over-broad set would reopen the bypass.
PAYLOAD_METADATA_KEYS = frozenset(
    {
        "agentDescription",
        "agentDisplayName",
        "agentId",
        "agentName",
        "agentType",
        "agent_display_name",
        "agent_id",
        "agent_name",
        "agent_type",
        "customInstructions",
        "cwd",
        "hookEventName",
        "hook_event_name",
        "initialPrompt",
        "initial_prompt",
        "last_assistant_message",
        "modifiedPrompt",
        "modifiedTransformedPrompt",
        "prompt",
        "reason",
        "recoverable",
        "response",
        "sessionId",
        "session_id",
        "source",
        "stopReason",
        "stop_hook_active",
        "stop_reason",
        "timestamp",
        "toolName",
        "tool_name",
        "transcriptPath",
        "transcript_path",
        "transformedPrompt",
        "trigger",
        *DISPATCH_ID_KEYS,
    }
)
PATCH_DIRECTIVE = re.compile(r"^\*\*\*\s*(?P<name>[^:]+):\s*(?P<value>.*)$")
KNOWN_PATCH_DIRECTIVES = {
    "add file",
    "delete file",
    "update file",
    "move to",
    "rename to",
}
# `*** Begin Patch` / `*** End Patch` carry no destination and are structural.
STRUCTURAL_PATCH_DIRECTIVES = {"begin patch", "end patch"}
SESSION_END_REASONS = {"complete", "error", "abort", "timeout", "user_exit"}
# Only these keys may reach the evidence ledger. Everything else is dropped so
# no prompt, model output, raw tool argument, secret, or PII is persisted.
EVIDENCE_KEYS = {
    "agent_role",
    "attempt",
    "backend",
    "command_index",
    "command_sha256",
    "contract_sha256",
    "decision",
    "digest",
    "duration_ms",
    "event",
    "executor",
    "exit_code",
    "mode",
    "nonce",
    "path_class",
    "purpose",
    "reason_code",
    "result",
    "run_id",
    "self_validating",
    "stderr_sha256",
    "stdout_sha256",
    "task_id",
    "timestamp",
    "tool_name",
}
# Closed vocabulary for `path_class`. It is a *classification*, never a path:
# the destination itself never reaches the ledger, so adding this key cannot
# weaken the sanitisation guarantee that no prompt, model output, raw tool
# argument, or secret is persisted.
PATH_CLASSES = frozenset(
    {
        "control-plane",
        "denied-subtree",
        "no-path",
        "not-write",
        "outside-repository",
        "out-of-ownership",
        "owned",
        "unreviewable",
    }
)
# Ceiling on canary-mode `preToolUse` allow records. The canary is one short
# session, but the ledger must stay bounded by construction rather than by
# expectation, so sealing stops after this many allows and the run fails closed
# on the coverage rule instead of growing an unbounded ledger.
CANARY_ALLOW_EVIDENCE_LIMIT = 64
EVIDENCE_VALUE = re.compile(r"^[A-Za-z0-9._:+-]{1,128}$")
# Keys whose values are legitimately long hex digests written by this handler.
# Every other string value is additionally screened for credential shapes, so
# a long opaque token can never be persisted even by a caller mistake.
EVIDENCE_DIGEST_KEYS = {
    "command_sha256",
    "contract_sha256",
    "digest",
    "nonce",
    "stderr_sha256",
    "stdout_sha256",
}
TERMINAL_STATUSES = {"PASS", "FAIL", "BLOCKED"}


class ControlPlaneError(RuntimeError):
    """The sealed control plane is missing, unreadable, or tampered."""


def utc_now() -> str:
    return datetime.now(UTC).isoformat()


def canonical_digest(value: Any) -> str:
    return fleet_policy.canonical_digest(value)


# ---------------------------------------------------------------------------
# Sealed control plane
# ---------------------------------------------------------------------------


def control_directory(contract: dict[str, Any]) -> Path:
    return Path(contract["control_directory"])


def repository_root(contract: dict[str, Any]) -> Path:
    return Path(contract["repository_root"])


def run_id(contract: dict[str, Any]) -> str:
    return str(contract.get("run_id") or control_directory(contract).name)


def verify_handler_integrity(contract: dict[str, Any]) -> None:
    """Fail closed when a pinned hook descriptor or handler byte has changed."""
    integrity = contract.get("integrity")
    if not isinstance(integrity, dict) or not integrity:
        raise ControlPlaneError("contract carries no handler integrity pins")
    root = repository_root(contract)
    for relative, expected in sorted(integrity.items()):
        path = root / str(relative)
        try:
            actual = fleet_policy.hashlib.sha256(path.read_bytes()).hexdigest()
        except OSError as exc:
            raise ControlPlaneError(
                f"pinned hook artifact is unreadable: {relative}"
            ) from exc
        if actual != str(expected):
            raise ControlPlaneError(
                f"pinned hook artifact changed during the run: {relative}"
            )


def load_contract(environ: dict[str, str] | None = None) -> dict[str, Any] | None:
    """Load and verify the sealed run contract, or return None when inert."""
    source = os.environ if environ is None else environ
    raw_path = source.get(CONTRACT_ENV, "").strip()
    if not raw_path:
        return None
    key = fleet_policy.hook_key(source)
    path = Path(raw_path).resolve()
    contract = fleet_policy.read_sealed_json(path, key)
    if contract.get("schema_version") != fleet_policy.CONTRACT_SCHEMA_VERSION:
        raise ControlPlaneError("unsupported fleet hook contract schema")
    if contract.get("mode") != fleet_policy.MODE_CONFINED_LITE:
        raise ControlPlaneError("only CONFINED_LITE fleet execution is supported")
    for field in ("repository_root", "control_directory"):
        value = contract.get(field)
        if not isinstance(value, str) or not Path(value).is_absolute():
            raise ControlPlaneError(f"contract {field} must be an absolute path")
    root = Path(contract["repository_root"]).resolve()
    control = Path(contract["control_directory"]).resolve()
    if fleet_policy.path_is_within(control, root):
        raise ControlPlaneError(
            "control directory must live outside the repository"
        )
    if not fleet_policy.path_is_within(path, control):
        raise ControlPlaneError("contract must live inside the control directory")
    if not isinstance(contract.get("selected_tasks"), list):
        raise ControlPlaneError("fleet hook contract has no selected_tasks list")
    verify_handler_integrity(contract)
    return contract


def state_path(contract: dict[str, Any]) -> Path:
    return control_directory(contract) / fleet_policy.STATE_NAME


def fresh_state() -> dict[str, Any]:
    return {
        "schema_version": fleet_policy.STATE_SCHEMA_VERSION,
        "tasks": {},
        "consecutive_blocks": 0,
    }


def load_state(contract: dict[str, Any]) -> dict[str, Any]:
    path = state_path(contract)
    if not path.is_file():
        return fresh_state()
    key = fleet_policy.hook_key()
    try:
        state = fleet_policy.read_sealed_json(path, key)
    except SealError as exc:
        fleet_policy.raise_abort(control_directory(contract), "state-tampered")
        raise ControlPlaneError(f"fleet hook state is not trustworthy: {exc}") from exc
    if state.get("schema_version") != fleet_policy.STATE_SCHEMA_VERSION:
        fleet_policy.raise_abort(control_directory(contract), "state-schema")
        raise ControlPlaneError("invalid fleet hook state schema")
    return state


def save_state(contract: dict[str, Any], state: dict[str, Any]) -> None:
    fleet_policy.write_sealed_json(
        state_path(contract), state, fleet_policy.hook_key()
    )


@contextmanager
def state_transaction(contract: dict[str, Any]) -> Iterator[dict[str, Any]]:
    """Hold the control-plane lock across one load → mutate → save cycle.

    Copilot issues parallel tool calls, so `preToolUse`/`postToolUse` hook
    processes overlap routinely. Without this, one handler's sealed write
    silently discards another's — including a quarantine flag or a fail-closed
    terminal status (finding N4). The lock is reentrant within a process, so a
    nested `record_evidence` append does not deadlock.

    The lock is deliberately *not* held across validation; long handlers commit
    a transaction, run their vectors unlocked, then merge through
    `commit_state`, which reloads under a fresh lock.
    """
    with fleet_policy.control_lock(control_directory(contract)):
        yield load_state(contract)


# Keys naming the single serial dispatch slot. They are owned by whichever
# handler holds the lock *now*, never by a snapshot taken before a long
# validation, so a quarantine recorded during validation survives the merge.
CONTROL_SLOT_KEYS = ("active_subagent", "pending_dispatch")
# Fail-closed precedence. A recorded BLOCKED outranks FAIL, which outranks
# PASS, so a concurrent fail-closed marker can never be relaxed by a stale
# in-memory object that still believed the task was passing.
TERMINAL_SEVERITY = {"PASS": 0, "FAIL": 1, "BLOCKED": 2}


def merge_state(
    fresh: dict[str, Any], stale: dict[str, Any]
) -> dict[str, Any]:
    """Merge a handler's in-memory state into freshly reloaded state.

    Deterministic validation can run for minutes, during which another hook
    process may quarantine a subagent or record a terminal status. Persisting
    the pre-validation object would silently discard that (finding N4), so the
    handler's own task fields are applied on top of the reloaded state while
    control slots and any equal-or-more-severe terminal status are taken from
    disk.
    """
    merged = dict(fresh)
    merged["schema_version"] = fleet_policy.STATE_SCHEMA_VERSION
    merged["consecutive_blocks"] = stale.get(
        "consecutive_blocks", fresh.get("consecutive_blocks", 0)
    )
    fresh_tasks = fresh.get("tasks", {}) or {}
    tasks = {
        task_id: dict(entry) for task_id, entry in fresh_tasks.items()
    }
    for task_id, entry in (stale.get("tasks", {}) or {}).items():
        target = tasks.setdefault(task_id, {})
        incoming = entry.get("terminal_status")
        target.update(entry)
        recorded = (fresh_tasks.get(task_id) or {}).get("terminal_status")
        if recorded in TERMINAL_SEVERITY and (
            incoming not in TERMINAL_SEVERITY
            or TERMINAL_SEVERITY[recorded] >= TERMINAL_SEVERITY[incoming]
        ):
            target["terminal_status"] = recorded
    merged["tasks"] = tasks
    for key in CONTROL_SLOT_KEYS:
        if key in fresh:
            merged[key] = fresh[key]
        else:
            merged.pop(key, None)
    return merged


def commit_state(
    contract: dict[str, Any], state: dict[str, Any]
) -> dict[str, Any]:
    """Reload under the lock, merge `state` into it, and seal the result.

    Used by every path that may have run a long validation since it loaded.
    The returned dictionary is the persisted state, so callers that keep
    reading it observe the merged view rather than their stale snapshot.
    """
    with fleet_policy.control_lock(control_directory(contract)):
        merged = merge_state(load_state(contract), state)
        save_state(contract, merged)
    state.clear()
    state.update(merged)
    return merged


def sanitize_evidence(event: dict[str, Any]) -> dict[str, Any]:
    """Reduce a ledger record to non-sensitive identifiers and status fields.

    Only `EVIDENCE_KEYS` survive. Digest-bearing keys may carry long hex, and
    every other string is both shape-checked and screened for credential
    patterns, so a prompt, model output, raw tool argument, run key, or secret
    cannot be persisted even if a caller passes one by mistake.
    """
    sanitized: dict[str, Any] = {}
    for key, value in event.items():
        if key not in EVIDENCE_KEYS:
            continue
        if isinstance(value, bool):
            sanitized[key] = value
        elif isinstance(value, int):
            sanitized[key] = value
        elif isinstance(value, str) and key == "timestamp":
            sanitized[key] = value
        elif not isinstance(value, str) or not EVIDENCE_VALUE.fullmatch(value):
            sanitized[key] = "REDACTED"
        elif key in EVIDENCE_DIGEST_KEYS:
            sanitized[key] = value
        elif fleet_policy.SECRET_TEXT.search(value):
            sanitized[key] = "REDACTED"
        else:
            sanitized[key] = value
    return sanitized


def record_evidence(contract: dict[str, Any], event: dict[str, Any]) -> None:
    """Append one sealed, hash-chained ledger record."""
    sanitized = sanitize_evidence(
        {"timestamp": utc_now(), "run_id": run_id(contract), **event}
    )
    try:
        fleet_policy.append_ledger(
            control_directory(contract), fleet_policy.hook_key(), sanitized
        )
    except (SealError, OSError) as exc:
        fleet_policy.raise_abort(control_directory(contract), "ledger-unwritable")
        raise ControlPlaneError(f"cannot seal fleet evidence: {exc}") from exc


# ---------------------------------------------------------------------------
# Payload parsing
# ---------------------------------------------------------------------------


def payload_agent_name(payload: dict[str, Any]) -> str:
    for key in ("agentName", "agent_name", "agentType", "agent_type"):
        value = payload.get(key)
        if isinstance(value, str) and value.strip():
            return value.strip()
    return ""


def payload_dispatch_id(payload: dict[str, Any]) -> str:
    """Return the runtime's subagent/dispatch identifier, or `""`.

    Copilot does not currently document a stable identifier on subagent
    lifecycle payloads. When one *is* present the gate binds the active slot to
    it, so a stale `subagentStop` from a previous dispatch cannot release the
    live one. When it is absent the gate falls back to the single-active-slot
    invariant plus the agent name, which is weaker: two dispatches of the same
    agent name are indistinguishable, and the second concurrent start is
    quarantined rather than correlated. That limitation is measurable — see
    `IdentityTests` — and is documented in `.github/harness/COPILOT-HARNESS.md`
    rather than papered over with a comparison that never runs.
    """
    for key in DISPATCH_ID_KEYS:
        value = payload.get(key)
        if isinstance(value, str) and value.strip():
            return value.strip()
    return ""


def payload_response(payload: dict[str, Any]) -> str:
    for key in ("response", "last_assistant_message"):
        value = payload.get(key)
        if isinstance(value, str):
            return value
    return ""


def payload_flag(payload: dict[str, Any], *keys: str) -> bool:
    return any(payload.get(key) is True for key in keys)


def normalize_tool_name(raw_name: str) -> str:
    name = raw_name.strip().lower()
    return CLAUDE_TOOL_ALIASES.get(name, name)


def residual_payload_targets(payload: dict[str, Any]) -> bool:
    """Report whether a payload's unrecognized containers expose a target.

    Called only when neither documented argument container is present. Every
    documented payload for a tool event carries `toolArgs`/`tool_input`, so a
    payload that carries a tool name without one is already anomalous. Rather
    than trusting it with empty arguments, sweep everything outside
    `PAYLOAD_METADATA_KEYS` for the same destination-path, patch-destination,
    and command shapes the policy checks, and report a hit so the caller can
    fail closed. Metadata-only payloads yield nothing, so a genuinely
    argument-free tool call stays reviewable and is still allowed.
    """
    residual = {
        key: value
        for key, value in payload.items()
        if key not in PAYLOAD_METADATA_KEYS
    }
    if not residual:
        return False
    paths, unknown_directives = candidate_paths(residual)
    return bool(paths or unknown_directives or candidate_commands(residual))


def reviewable_native_patch(patch: str) -> bool:
    """Recognize bounded native FREEFORM geometry, not write authority.

    Accept only add/delete/update hunks and an optional update move. The
    resulting patch still passes through the existing destination policy.
    Reject alternate line separators so its splitlines-based path scan sees
    exactly the same headers as the native LF-delimited patch.
    """
    if patch.splitlines() != patch.removesuffix("\n").split("\n"):
        return False
    destination = r"[^\s\x00-\x1f\x7f][^\x00-\x1f\x7f]*"
    add = rf"\*\*\* Add File: {destination}\n(?:\+[^\n]*\n)+"
    delete = rf"\*\*\* Delete File: {destination}\n"
    update = (
        rf"\*\*\* Update File: {destination}\n"
        rf"(?:\*\*\* Move to: {destination}\n)?"
        r"(?:@@(?: [^\n]*)?\n(?:[ +\-][^\n]*\n)+)+"
    )
    return re.fullmatch(
        rf"\*\*\* Begin Patch\n(?:{add}|{delete}|{update})+"
        r"\*\*\* End Patch\n?",
        patch,
    ) is not None


def payload_tool(payload: dict[str, Any]) -> tuple[str, dict[str, Any], bool]:
    """Return `(tool_name, arguments, reviewable)` for a tool payload.

    Only documented camelCase (`toolName`/`toolArgs`, and `toolInput` for
    `permissionRequest`) and VS Code compatible (`tool_name`/`tool_input`) keys
    are read. `permissionRequest` is the one event whose camelCase argument
    container is `toolInput` rather than `toolArgs` (hooks reference,
    "`permissionRequest` decision control"); omitting it made every write tool
    unreviewable at the permission layer and therefore denied. There is no
    permissive fallback. Native `apply_patch` (also reported as `edit` by
    the CLI hook) may carry a bounded
    FREEFORM patch string (raw or JSON-encoded) in one documented container;
    normalize it to `patch` without granting any destination authority:
    unresolvable arguments make `reviewable` False so the caller fails closed.
    That includes a payload whose arguments arrive in an *unrecognized*
    container: the container is not parsed as arguments, but it is swept for
    destination paths, patch destinations, and commands, and any hit is
    unreviewable. Otherwise a key such as `arguments` would reach the policy
    as `{}` and read a control-plane path that `candidate_paths` never saw.
    """
    name = ""
    native_patch_tool = False
    for key in ("toolName", "tool_name"):
        value = payload.get(key)
        if isinstance(value, str) and value.strip():
            name = normalize_tool_name(value)
            native_patch_tool = value.strip().lower() in {"apply_patch", "edit"}
            break
    argument_keys = [
        key for key in ("toolArgs", "toolInput", "tool_input") if key in payload
    ]
    if not argument_keys:
        return name, {}, not residual_payload_targets(payload)
    if len(argument_keys) != 1:
        return name, {}, False
    raw_arguments = payload[argument_keys[0]]
    if isinstance(raw_arguments, str):
        try:
            raw_arguments = json.loads(raw_arguments)
        except json.JSONDecodeError:
            if not native_patch_tool:
                return name, {}, False
    if isinstance(raw_arguments, str):
        if (
            not native_patch_tool
            or sum(key in payload for key in ("toolName", "tool_name")) != 1
            or any(
                key not in PAYLOAD_METADATA_KEYS
                or isinstance(value, (dict, list))
                for key, value in payload.items()
                if key not in argument_keys
            )
            or not reviewable_native_patch(raw_arguments)
        ):
            return name, {}, False
        raw_arguments = {"patch": raw_arguments}
    if raw_arguments is None:
        return name, {}, True
    if not isinstance(raw_arguments, dict):
        return name, {}, False
    return name, raw_arguments, True


def paths_from_patch(patch: str) -> tuple[list[str], list[str]]:
    """Return `(destinations, unknown_directives)` for an apply_patch body.

    Every `*** ` directive must be recognised. `Move to:` and `Rename to:`
    relocate content and are destinations exactly like `Add File:`, and an
    unrecognised directive is treated as an unreviewable destination.
    """
    destinations: list[str] = []
    unknown: list[str] = []
    for line in patch.splitlines():
        if not line.startswith("*** "):
            continue
        match = PATCH_DIRECTIVE.match(line)
        if match is None:
            name = line.removeprefix("*** ").strip().lower()
            if name not in STRUCTURAL_PATCH_DIRECTIVES:
                unknown.append(line.strip())
            continue
        name = match.group("name").strip().lower()
        value = match.group("value").strip()
        if name in STRUCTURAL_PATCH_DIRECTIVES:
            continue
        if name not in KNOWN_PATCH_DIRECTIVES:
            unknown.append(line.strip())
            continue
        if value:
            destinations.append(value)
    return destinations, unknown


def candidate_paths(arguments: dict[str, Any]) -> tuple[list[str], list[str]]:
    paths: list[str] = []
    unknown: list[str] = []
    pending: list[tuple[str, Any]] = [("", arguments)]
    while pending:
        key, value = pending.pop()
        if isinstance(value, dict):
            pending.extend(
                (str(child_key), child) for child_key, child in value.items()
            )
        elif isinstance(value, list):
            pending.extend((key, child) for child in value)
        elif isinstance(value, str):
            normalized_key = key.lower()
            if normalized_key in PATH_KEYS:
                paths.append(value)
            if normalized_key in PATCH_KEYS:
                destinations, directives = paths_from_patch(value)
                paths.extend(destinations)
                unknown.extend(directives)
    return paths, unknown


def candidate_commands(arguments: dict[str, Any]) -> list[str]:
    commands: list[str] = []
    pending: list[tuple[str, Any]] = [("", arguments)]
    while pending:
        key, value = pending.pop()
        if isinstance(value, dict):
            pending.extend(
                (str(child_key), child) for child_key, child in value.items()
            )
        elif isinstance(value, list):
            if key.lower() in COMMAND_KEYS and all(
                isinstance(item, str) for item in value
            ):
                commands.append(" ".join(value))
            pending.extend((key, child) for child in value)
        elif isinstance(value, str) and key.lower() in COMMAND_KEYS:
            commands.append(value)
    return commands


def dispatch_agent(arguments: dict[str, Any]) -> str:
    for key in AGENT_KEYS:
        value = arguments.get(key)
        if isinstance(value, str) and value.strip():
            return value.strip()
    return ""


# ---------------------------------------------------------------------------
# Contract helpers
# ---------------------------------------------------------------------------


def task_map(contract: dict[str, Any]) -> dict[str, dict[str, Any]]:
    return {
        str(task["id"]): task
        for task in contract["selected_tasks"]
        if isinstance(task, dict) and "id" in task
    }


def dispatch_order(contract: dict[str, Any]) -> list[str]:
    order = contract.get("dispatch_order")
    if isinstance(order, list) and order:
        return [str(item) for item in order]
    return list(task_map(contract))


def task_status(state: dict[str, Any], task_id: str) -> dict[str, Any]:
    tasks = state.setdefault("tasks", {})
    return tasks.setdefault(task_id, {})


def next_dispatch(
    contract: dict[str, Any], state: dict[str, Any]
) -> tuple[str, str] | None:
    """Return `(task_id, agent)` for the only dispatch the contract permits.

    The worker runs first; its validator becomes eligible only after the
    worker's deterministic validation passed. Anything else — including the
    built-in `general-purpose` agent, which emits no subagent lifecycle events
    at all — is denied.
    """
    tasks = task_map(contract)
    states = state.get("tasks", {})
    for task_id in dispatch_order(contract):
        task = tasks.get(task_id)
        if task is None or task.get("completed"):
            continue
        current = states.get(task_id, {})
        if current.get("terminal_status") in TERMINAL_STATUSES:
            continue
        if current.get("repair_required"):
            return task_id, str(task.get("agent", ""))
        if current.get("deterministic_validation") == "PASS":
            return task_id, str(task.get("validator_agent", ""))
        return task_id, str(task.get("agent", ""))
    return None


def write_scope(
    contract: dict[str, Any], state: dict[str, Any]
) -> tuple[list[dict[str, Any]], bool]:
    """Resolve the write scope for the registered active fleet subagent.

    Fail closed: with no registered, non-quarantined subagent the scope is
    empty and read-only. There is no union fallback, so an unregistered agent
    can never inherit another task's ownership or a read-only task's paths.
    """
    active = state.get("active_subagent")
    if not isinstance(active, dict) or active.get("mode") == "quarantine":
        return [], True
    task_id = str(active.get("task_id", ""))
    agent_name = str(active.get("agent_name", ""))
    task = task_map(contract).get(task_id)
    if task is None or task.get("completed"):
        return [], True
    if task.get("agent") != agent_name or task.get("read_only"):
        return [], True
    return [task], False


def allowed_write_roots(
    contract: dict[str, Any], tasks: list[dict[str, Any]]
) -> list[Path]:
    """Owned paths only. The artifact directory is never a write root."""
    root = repository_root(contract).resolve()
    return [
        fleet_policy.resolve_path(root, str(owned_path))
        for task in tasks
        for owned_path in task.get("owned_paths", [])
    ]


# ---------------------------------------------------------------------------
# Decisions
# ---------------------------------------------------------------------------


def deny(reason: str) -> dict[str, str]:
    return {"permissionDecision": "deny", "permissionDecisionReason": reason}


def denial(
    contract: dict[str, Any],
    reason_code: str,
    tool_name: str,
    reason: str,
    path_class: str = "",
) -> dict[str, str]:
    event: dict[str, Any] = {
        "event": "guardrail",
        "decision": "deny",
        "reason_code": reason_code,
        "tool_name": tool_name or "unknown",
    }
    if path_class:
        event["path_class"] = path_class
    record_evidence(contract, event)
    return deny(reason)


def terminal_block(reason: str) -> dict[str, str]:
    """End the turn deterministically instead of emitting another `block`."""
    return {
        "decision": "allow",
        "modifiedResponse": f"FLEET_RUN: BLOCKED\n{reason}",
    }


def allow(contract: dict[str, Any], state: dict[str, Any]) -> dict[str, str]:
    """Allow a stop event and reset the single global block counter."""
    state["consecutive_blocks"] = 0
    commit_state(contract, state)
    return {"decision": "allow"}


def block(
    contract: dict[str, Any], state: dict[str, Any], reason: str
) -> dict[str, Any]:
    """Emit a bounded `block`, or fail closed with a terminal decision.

    One global counter is shared by every stop hook. Copilot overrides the hook
    after `COPILOT_RUNAWAY_BLOCK_GUARD` consecutive blocks and discards the
    gate's decision, so the ceiling is strictly below it and the gate reaches
    its own terminal BLOCKED first.

    The counter and any fail-closed markers are written through `commit_state`,
    so a stop that follows a long validation merges into freshly reloaded state
    instead of resurrecting the pre-validation snapshot (finding N4).
    """
    budget = block_budget(contract)
    used = int(state.get("consecutive_blocks", 0)) + 1
    state["consecutive_blocks"] = used
    if used > budget:
        for task_id in incomplete_tasks(contract, state):
            task_status(state, task_id)["terminal_status"] = "BLOCKED"
        commit_state(contract, state)
        record_evidence(
            contract,
            {"event": "fleet-result", "result": "BLOCKED",
             "reason_code": "block-budget-exhausted"},
        )
        return terminal_block(
            "Continuation budget is exhausted below the Copilot runaway "
            "guard; stop and report the blocker."
        )
    commit_state(contract, state)
    return {"decision": "block", "reason": reason}


def block_budget(contract: dict[str, Any]) -> int:
    budgets = contract.get("budgets", {})
    requested = int(budgets.get("max_consecutive_blocks", fleet_policy.MAX_CONSECUTIVE_BLOCKS))
    return max(
        1,
        min(
            requested,
            fleet_policy.MAX_CONSECUTIVE_BLOCKS,
            COPILOT_RUNAWAY_BLOCK_GUARD - 1,
        ),
    )


# ---------------------------------------------------------------------------
# preToolUse policy
# ---------------------------------------------------------------------------


def evaluate_tool_call(
    contract: dict[str, Any],
    state: dict[str, Any],
    tool_name: str,
    arguments: dict[str, Any],
    *,
    reserve_dispatch: bool = True,
    dispatch_request_id: str = "",
) -> tuple[str, str] | None:
    """Return `(reason_code, reason)` to deny, or None to fall through."""
    root = repository_root(contract).resolve()
    control = control_directory(contract).resolve()
    paths, unknown_directives = candidate_paths(arguments)
    if unknown_directives:
        return (
            "unreviewable-write-destination",
            "patch contains an unrecognized `*** ` directive",
        )
    for raw_path in paths:
        if fleet_policy.path_is_within(
            fleet_policy.resolve_path(root, raw_path), control
        ):
            return (
                "control-plane-path",
                "the fleet control plane is not readable or writable by agents",
            )
    if tool_name in fleet_policy.SHELL_TOOLS:
        return (
            "confined-lite-shell-denied",
            "command tools are removed from fleet subagents in CONFINED_LITE; "
            "declared validation vectors run in the trusted gate instead",
        )
    if tool_name in fleet_policy.AGENT_MESSAGING_TOOLS:
        return (
            "agent-messaging-denied",
            "agent messaging tools are not available to fleet subagents",
        )
    if fleet_policy.is_mcp_tool(tool_name):
        return (
            "mcp-tool-denied",
            "MCP tool calls are denied by default for fleet subagents",
        )
    # Deny by argument shape as well as by name. No tool available to a
    # CONFINED_LITE fleet subagent legitimately takes a command string, so a
    # renamed or newly introduced command tool is denied even though its name
    # is not in `SHELL_TOOLS`. The tripwire only refines the reason code.
    for command in candidate_commands(arguments):
        if fleet_policy.FORBIDDEN_COMMAND.search(command):
            reason_code = (
                "protected-branch-push"
                if fleet_policy.PROTECTED_BRANCH_PUSH.search(command)
                else "forbidden-command"
            )
            return reason_code, "command is forbidden by the fleet contract"
        return (
            "command-shaped-tool",
            "command execution is not available to fleet subagents in "
            "CONFINED_LITE",
        )
    # N8 — ownership is decided by argument *shape*, not by tool name. Any
    # call that exposes a destination path or a patch destination is
    # ownership-checked, so a renamed, newly introduced, or entirely unknown
    # write tool cannot slip past by not being in `WRITE_TOOLS`. Only the
    # explicitly read-only path tools are exempt.
    exposes_destination = bool(paths) and tool_name not in READ_ONLY_PATH_TOOLS
    write_shaped = tool_name in fleet_policy.WRITE_TOOLS or exposes_destination
    gated = tool_name in fleet_policy.DISPATCH_TOOLS or write_shaped
    if gated and not canary_verified(contract):
        return (
            "canary-not-verified",
            "no verified live hook canary for this run; dispatch and writes "
            "are denied until the launcher proves the gate is loaded",
        )
    if tool_name in fleet_policy.DISPATCH_TOOLS:
        return evaluate_dispatch(
            contract,
            state,
            arguments,
            reserve=reserve_dispatch,
            request_id=dispatch_request_id,
        )
    if not write_shaped:
        return None
    if not paths:
        return (
            "unreviewable-write-destination",
            "write tool did not expose a reviewable destination path",
        )
    scoped_tasks, read_only = write_scope(contract, state)
    if read_only:
        return (
            "read-only-agent",
            "no writable fleet subagent is registered for this turn",
        )
    allowed = allowed_write_roots(contract, scoped_tasks)
    denied = fleet_policy.denied_write_targets(root, control)
    for raw_path in paths:
        path = fleet_policy.resolve_path(root, raw_path)
        if not fleet_policy.path_is_within(path, root):
            return (
                "write-escapes-repository",
                "write destination escapes the repository",
            )
        if any(fleet_policy.path_is_within(path, parent) for parent in denied):
            return (
                "write-denied-subtree",
                "write destination is a protected repository subtree",
            )
        if not any(
            fleet_policy.path_is_within(path, parent) for parent in allowed
        ):
            return (
                "write-outside-ownership",
                "write destination is outside the active task's ownership",
            )
    return None


def evaluate_dispatch(
    contract: dict[str, Any],
    state: dict[str, Any],
    arguments: dict[str, Any],
    *,
    reserve: bool = True,
    request_id: str = "",
) -> tuple[str, str] | None:
    if state.get("active_subagent"):
        return (
            "serial-subagent-profile",
            "a fleet subagent is already active; the memory-safe profile "
            "allows one active subagent at depth one",
        )
    agent_name = dispatch_agent(arguments)
    if not agent_name:
        return (
            "unregistered-dispatch",
            "dispatch did not name a contract custom agent",
        )
    expected = next_dispatch(contract, state)
    pending = state.get("pending_dispatch")
    if isinstance(pending, dict):
        duplicate_delivery = bool(state.get("duplicate_hook_delivery"))
        same_dispatch = (
            expected is not None
            and pending.get("task_id") == expected[0]
            and pending.get("agent") == agent_name
        )
        if (
            request_id
            and pending.get("request_id") == request_id
            and same_dispatch
        ):
            return None
        if (
            duplicate_delivery
            and same_dispatch
            and not pending.get("duplicate_pre_tool_accepted")
        ):
            pending["duplicate_pre_tool_accepted"] = True
            save_state(contract, state)
            return None
        # N5 — a dispatch that has not yet been consumed by a `subagentStart`
        # still owns the single slot. Without this, two `task` calls issued
        # before the first subagent starts would each install a pending
        # dispatch and the second would silently overwrite the first.
        return (
            "pending-dispatch-unconsumed",
            "a fleet dispatch is already pending and has not started yet; "
            "wait for it to begin before dispatching again",
        )
    if expected is None:
        return ("unregistered-dispatch", "no fleet task remains dispatchable")
    task_id, allowed_agent = expected
    if agent_name != allowed_agent:
        return (
            "unregistered-dispatch",
            f"only `{allowed_agent}` may be dispatched next for {task_id}",
        )
    if reserve:
        state["pending_dispatch"] = {
            "agent": agent_name,
            "task_id": task_id,
            "dispatch_id": uuid.uuid4().hex,
            "request_id": request_id,
            "at": utc_now(),
        }
        save_state(contract, state)
    return None


def canary_verified(contract: dict[str, Any]) -> bool:
    if contract.get("purpose") == fleet_policy.PURPOSE_CANARY:
        return True
    canary = contract.get("canary")
    return isinstance(canary, dict) and canary.get("status") == "PASS"


def canary_evidence_enabled(contract: dict[str, Any]) -> bool:
    """Report whether this run seals a record for *every* `preToolUse` verdict.

    Only a canary-purpose contract does. A real fleet run keeps the existing
    deny-only evidence shape, so nothing about production ledger volume or
    content changes; the canary is a disposable session whose whole job is to
    prove the boundary, and proving an *allow* happened is exactly the fact a
    deny-only ledger cannot carry.
    """
    return contract.get("purpose") == fleet_policy.PURPOSE_CANARY


def classify_tool_target(
    contract: dict[str, Any],
    state: dict[str, Any],
    tool_name: str,
    arguments: dict[str, Any],
) -> str:
    """Return a bounded, non-sensitive class for a call's write destination.

    The returned value is drawn from the closed `PATH_CLASSES` vocabulary and
    never contains a path, an argument, or any model text. It answers the one
    question a deny-only ledger cannot: *was this allowed call a write the
    active task owns, or a write outside it?* The ownership arithmetic mirrors
    `evaluate_tool_call` exactly so the class can never disagree with the
    verdict that was actually enforced.
    """
    root = repository_root(contract).resolve()
    control = control_directory(contract).resolve()
    paths, unknown_directives = candidate_paths(arguments)
    if unknown_directives:
        return "unreviewable"
    exposes_destination = bool(paths) and tool_name not in READ_ONLY_PATH_TOOLS
    if tool_name not in fleet_policy.WRITE_TOOLS and not exposes_destination:
        return "not-write"
    if not paths:
        return "no-path"
    scoped_tasks, read_only = write_scope(contract, state)
    allowed = [] if read_only else allowed_write_roots(contract, scoped_tasks)
    denied = fleet_policy.denied_write_targets(root, control)
    classification = "owned"
    for raw_path in paths:
        path = fleet_policy.resolve_path(root, raw_path)
        if fleet_policy.path_is_within(path, control):
            return "control-plane"
        if not fleet_policy.path_is_within(path, root):
            return "outside-repository"
        if any(fleet_policy.path_is_within(path, parent) for parent in denied):
            return "denied-subtree"
        if not any(
            fleet_policy.path_is_within(path, parent) for parent in allowed
        ):
            classification = "out-of-ownership"
    return classification


def seal_canary_allow(
    contract: dict[str, Any],
    state: dict[str, Any],
    tool_name: str,
    path_class: str,
) -> None:
    """Seal one bounded `preToolUse` allow record for a canary run.

    Bounded by construction: the counter lives in the sealed control-plane
    state, is incremented under the same lock that made the decision, and stops
    sealing at `CANARY_ALLOW_EVIDENCE_LIMIT`. Exhausting it cannot manufacture
    coverage — it can only withhold evidence, which fails the canary closed.
    """
    used = int(state.get("canary_allow_records", 0))
    if used >= CANARY_ALLOW_EVIDENCE_LIMIT:
        return
    state["canary_allow_records"] = used + 1
    save_state(contract, state)
    record_evidence(
        contract,
        {
            "event": "guardrail",
            "decision": "allow",
            "tool_name": tool_name or "unknown",
            "path_class": path_class,
        },
    )


def handle_pre_tool_use(
    payload: dict[str, Any], contract: dict[str, Any]
) -> dict[str, Any]:
    tool_name, arguments, reviewable = payload_tool(payload)
    if not reviewable:
        return denial(
            contract,
            "unreviewable-tool-arguments",
            tool_name,
            "tool arguments could not be reviewed by the fleet governance gate",
            path_class="unreviewable" if canary_evidence_enabled(contract) else "",
        )
    if fleet_policy.is_aborted(control_directory(contract)):
        return denial(
            contract,
            "control-plane-abort",
            tool_name,
            "the fleet control plane recorded a terminal abort",
        )
    # The whole decision — load, evaluate, any `pending_dispatch` write
    # `evaluate_dispatch` performs, and the canary classification — runs inside
    # one exclusive transaction, so two overlapping tool calls cannot both
    # claim the single dispatch slot and the class can never be computed
    # against a scope that a concurrent handler has already changed.
    canary_evidence = canary_evidence_enabled(contract)
    with state_transaction(contract) as state:
        verdict = evaluate_tool_call(
            contract,
            state,
            tool_name,
            arguments,
            dispatch_request_id=payload_dispatch_id(payload),
        )
        path_class = (
            classify_tool_target(contract, state, tool_name, arguments)
            if canary_evidence
            else ""
        )
        if verdict is None and canary_evidence:
            seal_canary_allow(contract, state, tool_name, path_class)
    if verdict is None:
        return {}
    reason_code, reason = verdict
    return denial(contract, reason_code, tool_name, reason, path_class)


def handle_permission_request(
    payload: dict[str, Any], contract: dict[str, Any]
) -> dict[str, Any]:
    """Decide at the permission layer, explicitly, in both directions.

    The permission hook fires *before* rule checks, session approvals, and user
    prompting, and "returning nothing falls through to normal permission
    handling" (hooks reference). A fleet session runs with `--no-ask-user`, so
    that fall-through cannot approve anything the CLI allow-list does not
    already cover — it silently denies. Every call the ownership policy has
    already accepted is therefore granted explicitly here, and everything else
    is denied. `evaluate_tool_call` remains the only authority: it has already
    rejected shell tools, MCP tools, control-plane paths, unregistered
    dispatches, and writes outside the active task's ownership, and
    `preToolUse` re-checks the same policy independently before execution.
    """
    tool_name, arguments, reviewable = payload_tool(payload)
    if not reviewable:
        return {
            "behavior": "deny",
            "message": "tool arguments could not be reviewed by the fleet gate",
        }
    if fleet_policy.is_aborted(control_directory(contract)):
        return {
            "behavior": "deny",
            "message": "the fleet control plane recorded a terminal abort",
        }
    canary_evidence = canary_evidence_enabled(contract)
    try:
        with state_transaction(contract) as state:
            verdict = evaluate_tool_call(
                contract,
                state,
                tool_name,
                arguments,
                reserve_dispatch=False,
            )
            path_class = (
                classify_tool_target(contract, state, tool_name, arguments)
                if canary_evidence
                else ""
            )
            if verdict is None and canary_evidence:
                # Canary only: record the fall-through too. Without it a
                # permission layer that denies an *owned* write before
                # `preToolUse` is indistinguishable from a model that never
                # called the tool, and the canary could not name its own
                # blocker.
                seal_canary_allow(contract, state, tool_name, path_class)
    except ControlPlaneError:
        return {
            "behavior": "deny",
            "message": "the fleet control plane is not trustworthy",
        }
    if verdict is None and tool_name and (
        tool_name in fleet_policy.WRITE_TOOLS
        or tool_name in fleet_policy.DISPATCH_TOOLS
        or tool_name in READ_ONLY_PATH_TOOLS
        or tool_name in {"skill", "ask_user", "update_todo", "sql"}
    ):
        return {"behavior": "allow"}
    reason_code, reason = verdict or (
        "unclassified-tool",
        "tool is not on the fleet allowlist",
    )
    event: dict[str, Any] = {
        "event": "permission-request",
        "decision": "deny",
        "reason_code": reason_code,
        "tool_name": tool_name or "unknown",
    }
    if path_class:
        event["path_class"] = path_class
    record_evidence(contract, event)
    return {"behavior": "deny", "message": reason}


def handle_mcp_tool_call(
    payload: dict[str, Any], contract: dict[str, Any]
) -> dict[str, Any]:
    """Deny every MCP tool call for fleet subagents."""
    tool_name, _, _ = payload_tool(payload)
    record_evidence(
        contract,
        {
            "event": "mcp-tool-call",
            "decision": "deny",
            "reason_code": "mcp-tool-denied",
            "tool_name": tool_name or "unknown",
        },
    )
    return {
        "permissionDecision": "deny",
        "permissionDecisionReason": (
            "MCP tool calls are denied by default for fleet subagents"
        ),
        "behavior": "deny",
        "message": "MCP tool calls are denied by default for fleet subagents",
    }


# ---------------------------------------------------------------------------
# Lifecycle
# ---------------------------------------------------------------------------


def handle_session_start(
    payload: dict[str, Any], contract: dict[str, Any]
) -> dict[str, Any]:
    """Write the launcher nonce into the sealed ledger.

    The launcher generated this nonce and holds it outside the repository. A
    hand-written artifact file cannot reproduce it, and the sealed hash chain
    means it cannot be replayed into a forged ledger either. The nonce is never
    injected into model-visible context.
    """
    with state_transaction(contract) as state:
        state["session_started_at"] = utc_now()
        start_count = int(state.get("session_start_count", 0))
        state["session_start_count"] = start_count + 1
        if start_count == 0:
            state.pop("active_subagent", None)
            state.pop("pending_dispatch", None)
        else:
            # Copilot CLI 1.0.82 on Linux delivers repository lifecycle hooks
            # twice for one non-interactive session. Mark the measured runtime
            # behavior so one matching preToolUse replay can be idempotent
            # without weakening the normal single-delivery dispatch guard.
            state["duplicate_hook_delivery"] = True
        save_state(contract, state)
    record_evidence(
        contract,
        {
            "event": "session-start",
            "contract_sha256": canonical_digest(contract),
            "nonce": str(contract.get("launcher_nonce", "")),
            "mode": str(contract.get("mode", "")),
            "purpose": str(contract.get("purpose", "")),
            "result": "STARTED",
        },
    )
    return {
        "additionalContext": (
            "Open Horizons runtime fleet gates are active in CONFINED_LITE. "
            "Command tools are unavailable; declared validation vectors run in "
            "the trusted gate. Task completion requires deterministic "
            "validation and independent review evidence."
        )
    }


def matching_tasks(
    contract: dict[str, Any], agent_name: str, field: str
) -> list[dict[str, Any]]:
    return [
        task
        for task in task_map(contract).values()
        if not task.get("completed") and task.get(field) == agent_name
    ]


def frozen_drift(contract: dict[str, Any], state: dict[str, Any]) -> list[str]:
    """Return PASS tasks whose owned content changed after they were frozen."""
    root = repository_root(contract)
    drifted: list[str] = []
    for task_id, task in task_map(contract).items():
        current = state.get("tasks", {}).get(task_id, {})
        frozen = current.get("frozen_digest")
        if not frozen:
            continue
        owned = [str(path) for path in task.get("owned_paths", [])]
        if fleet_policy.tree_digest(root, owned) != frozen:
            drifted.append(task_id)
    return drifted


QUARANTINE_CONTEXT = (
    "This subagent identity does not match the registered fleet dispatch. "
    "You are read-only: every write is denied. Return immediately and report "
    "the mismatch."
)


def quarantine_subagent(
    contract: dict[str, Any],
    state: dict[str, Any],
    agent_name: str,
    reason_code: str,
) -> dict[str, Any]:
    """Mark the active slot read-only and record why."""
    state["active_subagent"] = {
        "mode": "quarantine",
        "agent_name": agent_name,
        "reason_code": reason_code,
        "started_at": utc_now(),
    }
    save_state(contract, state)
    record_evidence(
        contract,
        {
            "event": "subagent-start",
            "agent_role": "quarantine",
            "reason_code": reason_code,
            "result": "QUARANTINED",
        },
    )
    return {"additionalContext": QUARANTINE_CONTEXT}


def handle_subagent_start(
    payload: dict[str, Any], contract: dict[str, Any]
) -> dict[str, Any]:
    agent_name = payload_agent_name(payload)
    dispatch_id = payload_dispatch_id(payload)
    with state_transaction(contract) as state:
        if fleet_policy.is_aborted(control_directory(contract)):
            # N9 — the abort marker short-circuits lifecycle handlers too, not
            # only `preToolUse`.
            return quarantine_subagent(
                contract, state, agent_name, "control-plane-abort"
            )
        drifted = frozen_drift(contract, state)
        if drifted:
            for task_id in drifted:
                task_status(state, task_id)["terminal_status"] = "BLOCKED"
            save_state(contract, state)
            record_evidence(
                contract,
                {
                    "event": "frozen-digest",
                    "result": "BLOCKED",
                    "reason_code": "post-pass-mutation",
                    "task_id": drifted[0],
                },
            )
            return {
                "additionalContext": (
                    "FLEET_RUN: BLOCKED\nA task that already passed was "
                    "modified after validation. Stop and report the blocker."
                )
            }
        active = state.get("active_subagent")
        if isinstance(active, dict):
            recorded_dispatch_id = str(active.get("runtime_dispatch_id", ""))
            duplicate_start = (
                bool(state.get("duplicate_hook_delivery"))
                and active.get("agent_name") == agent_name
                and active.get("mode") != "quarantine"
                and not active.get("duplicate_start_accepted")
                and (
                    not recorded_dispatch_id
                    or not dispatch_id
                    or recorded_dispatch_id == dispatch_id
                )
            )
            if duplicate_start:
                active["duplicate_start_accepted"] = True
                save_state(contract, state)
                return {}
            # N5 — a second concurrent start is quarantined rather than
            # allowed to take over the single writable slot.
            return quarantine_subagent(
                contract, state, agent_name, "concurrent-subagent"
            )
        pending = state.get("pending_dispatch")
        if not isinstance(pending, dict) or pending.get("agent") != agent_name:
            return quarantine_subagent(
                contract, state, agent_name, "identity-mismatch"
            )
        task_id = str(pending.get("task_id", ""))
        task = task_map(contract).get(task_id, {})
        role = "worker" if task.get("agent") == agent_name else "validator"
        state["active_subagent"] = {
            "agent_name": agent_name,
            "task_id": task_id,
            # Prefer the runtime's own identifier when it supplies one; fall
            # back to the launcher-minted dispatch id otherwise.
            "dispatch_id": dispatch_id or pending.get("dispatch_id"),
            "runtime_dispatch_id": dispatch_id,
            "started_at": utc_now(),
        }
        # N5 — consume the pending dispatch at the *first* matching start, so
        # a replayed `subagentStart` finds no pending dispatch and is
        # quarantined by the identity-mismatch branch above.
        state.pop("pending_dispatch", None)
        save_state(contract, state)
    record_evidence(
        contract,
        {
            "event": "subagent-start",
            "agent_role": role,
            "task_id": task_id,
            "result": "STARTED",
        },
    )
    lines = [
        "Runtime fleet gate is active in CONFINED_LITE. Command tools are "
        "unavailable; the hook independently reruns the declared argv "
        "validation vectors and reports failures back to you.",
    ]
    if role == "worker":
        lines.append(
            f"Worker task {task_id}: owned_paths={task.get('owned_paths', [])}; "
            f"finish with `FLEET_RESULT: {task_id}: PASS|FAIL|BLOCKED`."
        )
    else:
        lines.append(
            f"Validator task {task_id}: remain read-only; finish with "
            f"`FLEET_VALIDATION: {task_id}: PASS|FAIL`."
        )
    return {"additionalContext": "\n".join(lines)}


def handle_post_tool_use(
    payload: dict[str, Any], contract: dict[str, Any]
) -> dict[str, Any]:
    tool_name, _, _ = payload_tool(payload)
    record_evidence(
        contract,
        {
            "event": "tool-result",
            "tool_name": tool_name or "unknown",
            "result": "PASS",
        },
    )
    return {}


def handle_post_tool_use_failure(
    payload: dict[str, Any], contract: dict[str, Any]
) -> dict[str, Any]:
    tool_name, _, _ = payload_tool(payload)
    record_evidence(
        contract,
        {
            "event": "tool-result",
            "tool_name": tool_name or "unknown",
            "result": "FAIL",
        },
    )
    return {
        "additionalContext": (
            "The tool failed. Repair the same bounded task and return the "
            "exact marker again; the gate reruns the declared validation "
            "vectors itself."
        )
    }


def handle_session_end(
    payload: dict[str, Any], contract: dict[str, Any]
) -> dict[str, Any]:
    raw_reason = payload.get("reason")
    reason = (
        raw_reason
        if isinstance(raw_reason, str) and raw_reason in SESSION_END_REASONS
        else "unknown"
    )
    record_evidence(contract, {"event": "session-end", "result": reason})
    return {}


# ---------------------------------------------------------------------------
# Deterministic validation
# ---------------------------------------------------------------------------


def descriptor_timeout_seconds(root: Path) -> int:
    """Read the `subagentStop` descriptor timeout at runtime."""
    try:
        payload = json.loads(
            (root / VALIDATION_GATE_DESCRIPTOR).read_text(encoding="utf-8")
        )
    except (OSError, json.JSONDecodeError):
        return 900
    entries = payload.get("hooks", {}).get("subagentStop", [])
    timeouts = [
        entry.get("timeoutSec")
        for entry in entries
        if isinstance(entry, dict)
        and isinstance(entry.get("timeoutSec"), int)
        and not isinstance(entry.get("timeoutSec"), bool)
    ]
    return min(timeouts) if timeouts else 900


def validation_deadline(contract: dict[str, Any]) -> float:
    """Clamp the contract budget to the descriptor timeout minus a margin.

    A hook timeout is always fail-open, so the handler must finish first. The
    deadline is measured from process start so pre-validation git work is
    inside the same budget.
    """
    root = repository_root(contract)
    ceiling = descriptor_timeout_seconds(root) - fleet_policy.VALIDATION_BUDGET_MARGIN_SECONDS
    budgets = contract.get("budgets", {})
    requested = int(budgets.get("validation_budget_seconds", ceiling))
    budget = max(1, min(requested, max(1, ceiling)))
    return PROCESS_START + budget


def validation_overlay(
    contract: dict[str, Any], task: dict[str, Any]
) -> list[str]:
    """Return authorized paths for the task and its dependency closure.

    The candidate task and every declared dependency are overlaid onto the
    disposable base-revision worktree. Unrelated task paths and validator
    scripts remain pristine `base_head` content, so agent-authored code cannot
    decide its own verdict while later tasks can validate against approved
    dependency output.
    """
    tasks = task_map(contract)
    overlay: list[str] = []
    visited: set[str] = set()

    def visit(task_id: str) -> None:
        if task_id in visited:
            return
        visited.add(task_id)
        current = tasks.get(task_id)
        if current is None:
            return
        for dependency in current.get("depends_on", []):
            visit(str(dependency))
        for path in current.get("owned_paths", []):
            normalized = str(path)
            if normalized not in overlay:
                overlay.append(normalized)

    visit(str(task["id"]))
    return overlay


def run_validation_commands(
    contract: dict[str, Any], task: dict[str, Any], attempt: int
) -> tuple[bool, str]:
    """Run a task's declared argv vectors inside one sandboxed worktree.

    Every vector executes through `fleet_sandbox`: a probed OS sandbox, a
    disposable `git worktree` at `base_head` carrying only this task's owned
    paths, and a secret-free environment. There is no unsandboxed fallback —
    if no backend can be proven, the result is a deterministic BLOCKED.
    """
    root = repository_root(contract)
    deadline = validation_deadline(contract)
    commands = [list(command) for command in task.get("validation_commands", [])]
    # Every vector is argv-checked before any workspace is built, so a policy
    # violation anywhere in the list prevents the whole run rather than only
    # the offending command.
    for index, command in enumerate(commands, start=1):
        try:
            fleet_policy.validate_vector(command, root)
        except PolicyError as exc:
            return False, f"validation command {index} violates argv policy: {exc}"
    if not commands:
        return True, ""
    task_id = str(task["id"])
    try:
        workspace = fleet_sandbox.ValidationWorkspace(
            root,
            str(contract.get("base_head", "")),
            overlay=validation_overlay(contract, task),
            control_directory=control_directory(contract),
        )
        workspace.__enter__()
    except (
        fleet_sandbox.SandboxUnavailable,
        fleet_sandbox.WorktreeError,
        fleet_sandbox.EnvironmentLeak,
        OSError,
        subprocess.SubprocessError,
    ) as exc:
        record_evidence(
            contract,
            {
                "event": "validation-sandbox",
                "task_id": task_id,
                "attempt": attempt,
                "backend": fleet_sandbox.describe_backend(),
                "result": "BLOCKED",
                "reason_code": "sandbox-unavailable",
            },
        )
        return False, (
            "validation cannot run without a proven execution sandbox: "
            f"{fleet_policy.redact_text(str(exc))}"
        )
    try:
        record_evidence(
            contract,
            {
                "event": "validation-sandbox",
                "task_id": task_id,
                "attempt": attempt,
                "backend": workspace.backend,
                "executor": "disposable-worktree",
                "result": "STARTED",
            },
        )
        for index, command in enumerate(commands, start=1):
            started = time.monotonic()
            remaining = deadline - started
            command_record = {
                "event": "validation-command",
                "task_id": task_id,
                "attempt": attempt,
                "command_index": index,
                "command_sha256": canonical_digest(command),
                "backend": workspace.backend,
                "executor": "disposable-worktree",
            }
            record_evidence(contract, {**command_record, "result": "STARTED"})
            if remaining <= 0:
                record_evidence(
                    contract,
                    {**command_record, "duration_ms": 0, "result": "BLOCKED"},
                )
                return False, (
                    f"validation budget was exhausted before command {index}"
                )
            try:
                result = workspace.run(command, timeout=remaining)
            except (
                OSError,
                subprocess.SubprocessError,
                fleet_sandbox.SandboxUnavailable,
                fleet_sandbox.EnvironmentLeak,
            ):
                record_evidence(
                    contract,
                    {
                        **command_record,
                        "duration_ms": int((time.monotonic() - started) * 1000),
                        "result": "BLOCKED",
                    },
                )
                return False, f"validation command {index} could not complete"
            record_evidence(
                contract,
                {
                    **command_record,
                    "duration_ms": int((time.monotonic() - started) * 1000),
                    "exit_code": result.returncode,
                    "stdout_sha256": fleet_policy.hashlib.sha256(
                        result.stdout
                    ).hexdigest(),
                    "stderr_sha256": fleet_policy.hashlib.sha256(
                        result.stderr
                    ).hexdigest(),
                    "result": "PASS" if result.returncode == 0 else "FAIL",
                },
            )
            if result.returncode != 0:
                excerpt = fleet_policy.bounded_excerpt(
                    result.stderr or result.stdout
                )
                return False, (
                    f"validation command {index} failed with exit "
                    f"{result.returncode}: {excerpt}"
                )
        return True, ""
    finally:
        workspace.close()


def changed_paths(root: Path) -> list[str]:
    result = subprocess.run(
        ["git", "status", "--porcelain=v1", "-z", "--untracked-files=all"],
        cwd=root,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
        env={**fleet_policy.scrub_environment(), "GIT_OPTIONAL_LOCKS": "0"},
    )
    if result.returncode != 0:
        raise RuntimeError("cannot inspect repository changes")
    entries = result.stdout.split(b"\0")
    paths: set[str] = set()
    index = 0
    while index < len(entries):
        raw_entry = entries[index]
        index += 1
        if not raw_entry:
            continue
        entry = raw_entry.decode("utf-8", errors="surrogateescape")
        status = entry[:2]
        paths.add(entry[3:])
        if "R" in status or "C" in status:
            if index < len(entries) and entries[index]:
                paths.add(
                    entries[index].decode("utf-8", errors="surrogateescape")
                )
                index += 1
    return sorted(paths)


def unexpected_changed_paths(
    contract: dict[str, Any], state: dict[str, Any], task: dict[str, Any]
) -> list[str]:
    """Scope check against the active task's ownership only.

    Another task's tree may differ from its baseline only while that task is
    the one being worked; once a task is frozen at PASS, `frozen_drift` owns
    it. There is no accepted-owned fallback that permanently widens scope.
    """
    root = repository_root(contract)
    owned = [str(path) for path in task.get("owned_paths", [])]
    baseline = contract.get("baseline", {}).get("tasks", {})
    tolerated = list(owned)
    artifact = Path(contract.get("artifact_directory", ""))
    if artifact.is_absolute() and fleet_policy.path_is_within(
        artifact.resolve(), root.resolve()
    ):
        # The launcher and the CLI write logs, prompts, and usage data here.
        # Agents are denied every write to it, so its contents are never an
        # ownership violation — and treating them as one would make a run
        # self-block whenever `.test-results/` is not git-ignored.
        tolerated.append(
            artifact.resolve().relative_to(root.resolve()).as_posix()
        )
    for other_id, other in task_map(contract).items():
        if other_id == str(task.get("id")):
            continue
        other_owned = [str(path) for path in other.get("owned_paths", [])]
        if not other_owned:
            continue
        recorded = state.get("tasks", {}).get(other_id, {}).get("frozen_digest")
        expected = recorded or baseline.get(other_id)
        if expected and fleet_policy.tree_digest(root, other_owned) == expected:
            tolerated.extend(other_owned)
    return [
        path
        for path in changed_paths(root)
        if not fleet_policy.path_matches_owned(path, tolerated)
    ]


def binding_failure(contract: dict[str, Any]) -> str:
    baseline = contract.get("baseline", {}).get("repo_binding", {})
    if not baseline:
        return ""
    return fleet_policy.binding_drift(
        baseline, fleet_policy.repository_binding(repository_root(contract))
    )


def parse_unique_result(
    response: str, pattern: re.Pattern[str]
) -> tuple[str, str] | None:
    matches = pattern.findall(response)
    return matches[0] if len(matches) == 1 else None


def result_detail(response: str, marker: str) -> str:
    """Return non-marker evidence attached to a terminal worker result."""

    return "\n".join(
        line.strip()
        for line in response.splitlines()
        if line.strip() and line.strip() != marker
    ).strip()


def finish_task(
    contract: dict[str, Any],
    state: dict[str, Any],
    task_id: str,
    field: str,
    status: str,
    marker: str,
    reason: str = "",
) -> dict[str, Any]:
    current = task_status(state, task_id)
    current[field] = status
    current["terminal_status"] = status
    state["consecutive_blocks"] = 0
    # Merge rather than overwrite: this often runs after a multi-minute
    # validation, and a more severe terminal status recorded meanwhile wins.
    merged = commit_state(contract, state)
    persisted = merged.get("tasks", {}).get(task_id, {}).get(
        "terminal_status", status
    )
    record_evidence(
        contract,
        {
            "event": field.replace("_", "-"),
            "task_id": task_id,
            "result": persisted,
        },
    )
    body = f"{marker}: {task_id}: {persisted}"
    if reason:
        body = f"{body}\n{reason}"
    return {"decision": "allow", "modifiedResponse": body}


def handle_worker_stop(
    payload: dict[str, Any],
    contract: dict[str, Any],
    state: dict[str, Any],
    task: dict[str, Any],
) -> dict[str, Any]:
    task_id = str(task["id"])
    response = payload_response(payload)
    parsed = parse_unique_result(response, WORKER_RESULT)
    if parsed is None or parsed[0] != task_id:
        return block(
            contract,
            state,
            f"Finish with exactly one `FLEET_RESULT: {task_id}: "
            "PASS|FAIL|BLOCKED` marker for your assigned task.",
        )
    status = parsed[1]
    drift = binding_failure(contract)
    if drift:
        return finish_task(
            contract, state, task_id, "worker_result", "FAIL",
            "FLEET_RESULT", drift,
        )
    unexpected = unexpected_changed_paths(contract, state, task)
    if unexpected:
        task_status(state, task_id)["scope"] = "FAIL"
        return block(
            contract,
            state,
            "Remove changes outside task ownership before returning: "
            + ", ".join(unexpected[:20]),
        )
    if status in {"FAIL", "BLOCKED"}:
        marker = f"FLEET_RESULT: {task_id}: {status}"
        detail = result_detail(response, marker)
        if not detail:
            return block(
                contract,
                state,
                f"`{marker}` requires a concrete blocker or failure detail. "
                "Continue in the same worker slot, finish any remaining "
                "owned work, and return the marker with evidence.",
            )
        return finish_task(
            contract,
            state,
            task_id,
            "worker_result",
            status,
            "FLEET_RESULT",
            detail,
        )
    owned = [str(path) for path in task.get("owned_paths", [])]
    if task.get("read_only") and any(
        fleet_policy.path_matches_owned(path, owned)
        for path in changed_paths(repository_root(contract))
    ):
        return finish_task(
            contract, state, task_id, "worker_result", "FAIL", "FLEET_RESULT",
            "Read-only task changed an owned path.",
        )
    current = task_status(state, task_id)
    attempt = int(current.get("worker_validation_attempts", 0)) + 1
    current["worker_validation_attempts"] = attempt
    pre_digest = fleet_policy.tree_digest(repository_root(contract), owned)
    current["pre_validation_digest"] = pre_digest
    # Persist the in-flight marker before the first subprocess starts. A hook
    # timeout is fail-open, so this record is what stops a killed validation
    # from being mistaken for a completed one.
    current["deterministic_validation"] = "IN_FLIGHT"
    commit_state(contract, state)

    # The control lock is deliberately released here: validation can run for
    # minutes and holding it would serialise every other hook process.
    passed, reason = run_validation_commands(contract, task, attempt)

    # Reload under a fresh lock before deciding anything. Another hook process
    # may have quarantined this subagent or recorded a fail-closed terminal
    # status while the vectors ran, and that must not be overwritten by the
    # pre-validation snapshot (finding N4).
    commit_state(contract, state)
    current = task_status(state, task_id)
    recorded = current.get("terminal_status")
    if recorded in TERMINAL_STATUSES:
        record_evidence(
            contract,
            {
                "event": "worker-result",
                "task_id": task_id,
                "result": recorded,
                "reason_code": "concurrent-terminal-status",
            },
        )
        return terminal_block(
            f"{task_id} was recorded {recorded} while deterministic "
            "validation was running. Stop and report the blocker."
        )
    post_digest = fleet_policy.tree_digest(repository_root(contract), owned)
    current["post_validation_digest"] = post_digest
    if post_digest != pre_digest:
        current["deterministic_validation"] = "FAIL"
        return finish_task(
            contract, state, task_id, "worker_result", "FAIL", "FLEET_RESULT",
            "Owned content changed while deterministic validation was running.",
        )
    # N3 — re-run unexpected-path detection *after* validation as well as
    # before it, so a write that landed while the vectors ran is still caught.
    unexpected = unexpected_changed_paths(contract, state, task)
    if unexpected:
        task_status(state, task_id)["scope"] = "FAIL"
        return finish_task(
            contract, state, task_id, "worker_result", "FAIL", "FLEET_RESULT",
            "Changes outside task ownership appeared during validation: "
            + ", ".join(unexpected[:20]),
        )
    if not passed:
        current["deterministic_validation"] = "FAIL"
        budget = int(contract.get("budgets", {}).get("max_validation_loops", 0))
        if attempt <= budget:
            return block(
                contract,
                state,
                f"{reason}; repair the task and return the exact marker again.",
            )
        return finish_task(
            contract, state, task_id, "worker_result", "FAIL", "FLEET_RESULT",
            f"{reason}; validation loop budget exhausted.",
        )
    current.update(
        {
            "deterministic_validation": "PASS",
            "worker_digest": post_digest,
            "worker_result": "PASS",
            "repair_required": False,
        }
    )
    state["consecutive_blocks"] = 0
    commit_state(contract, state)
    record_evidence(
        contract,
        {
            "event": "worker-result",
            "task_id": task_id,
            "result": "PASS",
            "digest": post_digest,
        },
    )
    return {"decision": "allow"}


def handle_validator_stop(
    payload: dict[str, Any],
    contract: dict[str, Any],
    state: dict[str, Any],
    task: dict[str, Any],
) -> dict[str, Any]:
    task_id = str(task["id"])
    response = payload_response(payload)
    parsed = parse_unique_result(response, VALIDATOR_RESULT)
    if parsed is None or parsed[0] != task_id:
        return block(
            contract,
            state,
            f"Finish with exactly one `FLEET_VALIDATION: {task_id}: PASS|FAIL` "
            "marker for your assigned task.",
        )
    status = parsed[1]
    drift = binding_failure(contract)
    if drift:
        return finish_task(
            contract, state, task_id, "validator_result", "FAIL",
            "FLEET_VALIDATION", drift,
        )
    current = task_status(state, task_id)
    if current.get("deterministic_validation") != "PASS":
        return block(
            contract,
            state,
            "Independent review cannot pass before deterministic validation "
            "evidence exists.",
        )
    owned = [str(path) for path in task.get("owned_paths", [])]
    current_digest = fleet_policy.tree_digest(repository_root(contract), owned)
    if current_digest != current.get("worker_digest"):
        return block(
            contract,
            state,
            "Reviewed content changed after deterministic validation; restore "
            "read-only separation.",
        )
    attempts = int(current.get("validator_attempts", 0)) + 1
    current["validator_attempts"] = attempts
    current["validator_result"] = status
    if status == "PASS":
        current["terminal_status"] = "PASS"
        current["frozen_digest"] = current_digest
        current["repair_required"] = False
    elif attempts > int(
        contract.get("budgets", {}).get("max_validation_loops", 0)
    ):
        current["terminal_status"] = "FAIL"
    else:
        current["repair_required"] = True
        current["deterministic_validation"] = "REPAIR_REQUIRED"
        current["worker_digest"] = None
        current["worker_result"] = "REPAIR_REQUIRED"
    state["consecutive_blocks"] = 0
    merged = commit_state(contract, state)
    persisted = merged.get("tasks", {}).get(task_id, {}).get(
        "terminal_status", current.get("terminal_status")
    )
    record_evidence(
        contract,
        {
            "event": "validator-result",
            "task_id": task_id,
            "result": status if persisted != "BLOCKED" else "BLOCKED",
            "digest": current_digest,
        },
    )
    return {"decision": "allow"}


def stop_matches_active_slot(
    active: Any, agent_name: str, dispatch_id: str
) -> bool:
    """Decide whether a `subagentStop` really belongs to the active slot.

    N5 — the slot must not be released by a stale or mismatched stop. When the
    runtime supplies a dispatch identifier it is authoritative and must match
    exactly. When it does not, the agent name plus the single-active-slot
    invariant is the only available correlation; the gate does not pretend an
    identifier was compared.
    """
    if not isinstance(active, dict):
        return False
    if active.get("agent_name") != agent_name:
        return False
    recorded = active.get("runtime_dispatch_id")
    if isinstance(recorded, str) and recorded:
        return dispatch_id == recorded
    if dispatch_id and isinstance(recorded, str) and not recorded:
        # The slot was opened without a runtime identifier but this stop
        # carries one: the two cannot be correlated, so fail closed.
        return False
    return True


def restore_active_slot_for_continuation(
    contract: dict[str, Any], active: dict[str, Any]
) -> None:
    """Restore the same subagent's authority after a bounded stop-hook block.

    `handle_subagent_stop` releases the serial slot before running validation so
    duplicate stop delivery cannot execute the same vectors twice. When the
    validation result is repairable, Copilot resumes the *same* subagent rather
    than issuing a new `task` dispatch. Leaving the slot empty made that
    continuation read-only, so its first repair edit was denied. Restore only
    the captured matching slot, only when no other subagent claimed it, and
    never after a terminal task result.
    """
    task_id = str(active.get("task_id", ""))
    with state_transaction(contract) as state:
        terminal = (
            task_status(state, task_id).get("terminal_status")
            if task_id
            else None
        )
        if state.get("active_subagent") or terminal in TERMINAL_STATUSES:
            return
        state["active_subagent"] = dict(active)
        state.pop("pending_dispatch", None)
        save_state(contract, state)


def handle_subagent_stop(
    payload: dict[str, Any], contract: dict[str, Any]
) -> dict[str, Any]:
    agent_name = payload_agent_name(payload)
    dispatch_id = payload_dispatch_id(payload)
    aborted = fleet_policy.is_aborted(control_directory(contract))
    with state_transaction(contract) as state:
        active = state.get("active_subagent")
        quarantined = (
            isinstance(active, dict) and active.get("mode") == "quarantine"
        )
        task_id = (
            str(active.get("task_id", "")) if isinstance(active, dict) else ""
        )
        owns_slot = stop_matches_active_slot(active, agent_name, dispatch_id)
        if owns_slot:
            # Release the serial slot first so a blocked continuation can still
            # dispatch its repair turn under the one-active-subagent profile.
            state.pop("active_subagent", None)
            state.pop("pending_dispatch", None)
            save_state(contract, state)
        elif isinstance(active, dict):
            # N5 — a stale or mismatched stop must not free the live slot.
            record_evidence(
                contract,
                {
                    "event": "subagent-stop",
                    "agent_role": "unassigned",
                    "reason_code": "stale-subagent-stop",
                    "result": "SKIPPED",
                },
            )
            return terminal_block(
                "This subagent stop does not match the active fleet dispatch "
                "and cannot release it."
            )
        drifted = frozen_drift(contract, state)
        if drifted:
            for drifted_id in drifted:
                task_status(state, drifted_id)["terminal_status"] = "BLOCKED"
            save_state(contract, state)
            record_evidence(
                contract,
                {
                    "event": "frozen-digest",
                    "result": "BLOCKED",
                    "reason_code": "post-pass-mutation",
                    "task_id": drifted[0],
                },
            )
            return terminal_block(
                "A task that already passed was modified after validation."
            )
        if aborted:
            # N9 — honour the abort marker in the stop handlers as well as in
            # `preToolUse`, so a tampered control plane ends the turn instead
            # of running another multi-minute validation.
            record_evidence(
                contract,
                {
                    "event": "subagent-stop",
                    "reason_code": "control-plane-abort",
                    "result": "BLOCKED",
                },
            )
            return terminal_block(
                "The fleet control plane recorded a terminal abort. Stop and "
                "report the blocker."
            )
        if quarantined or not task_id:
            record_evidence(
                contract,
                {
                    "event": "subagent-stop",
                    "agent_role": "quarantine" if quarantined else "unassigned",
                    "result": "SKIPPED",
                },
            )
            return allow(contract, state)
        task = task_map(contract).get(task_id)
        if task is None:
            return allow(contract, state)
        is_worker = task.get("agent") == agent_name
        is_validator = task.get("validator_agent") == agent_name
        if not is_worker and not is_validator:
            record_evidence(
                contract,
                {
                    "event": "subagent-stop",
                    "agent_role": "unassigned",
                    "result": "SKIPPED",
                },
            )
            return allow(contract, state)
    # The lock is released before validation: `handle_worker_stop` runs the
    # declared vectors and then merges into freshly reloaded state.
    result = (
        handle_worker_stop(payload, contract, state, task)
        if is_worker
        else handle_validator_stop(payload, contract, state, task)
    )
    if result.get("decision") == "block" and isinstance(active, dict):
        restore_active_slot_for_continuation(contract, active)
    return result


def incomplete_tasks(
    contract: dict[str, Any], state: dict[str, Any]
) -> list[str]:
    incomplete: list[str] = []
    states = state.get("tasks", {})
    for task_id, task in task_map(contract).items():
        if task.get("completed"):
            continue
        current = states.get(task_id, {})
        if current.get("deterministic_validation") == "IN_FLIGHT":
            incomplete.append(task_id)
            continue
        if current.get("terminal_status") in TERMINAL_STATUSES:
            continue
        incomplete.append(task_id)
    return incomplete


def aggregate_status(contract: dict[str, Any], state: dict[str, Any]) -> str:
    # Default to BLOCKED, never PASS: a task with no recorded terminal status
    # has no evidence, and a missing record must not read as success.
    statuses = [
        state.get("tasks", {}).get(task_id, {}).get("terminal_status", "BLOCKED")
        for task_id, task in task_map(contract).items()
        if not task.get("completed")
    ]
    if "BLOCKED" in statuses:
        return "BLOCKED"
    if "FAIL" in statuses:
        return "FAIL"
    return "PASS"


def handle_agent_stop(
    payload: dict[str, Any], contract: dict[str, Any]
) -> dict[str, Any]:
    forced = payload_flag(payload, "stop_hook_active", "stopHookActive")
    aborted = fleet_policy.is_aborted(control_directory(contract))
    with state_transaction(contract) as state:
        if aborted:
            # N9 — the abort marker is terminal for the agent stop too.
            for task_id in incomplete_tasks(contract, state):
                task_status(state, task_id)["terminal_status"] = "BLOCKED"
            save_state(contract, state)
            record_evidence(
                contract,
                {
                    "event": "fleet-result",
                    "result": "BLOCKED",
                    "reason_code": "control-plane-abort",
                },
            )
            return terminal_block(
                "The fleet control plane recorded a terminal abort. Stop and "
                "report the blocker."
            )
        drifted = frozen_drift(contract, state)
        if drifted:
            for task_id in drifted:
                task_status(state, task_id)["terminal_status"] = "BLOCKED"
            save_state(contract, state)
            record_evidence(
                contract,
                {
                    "event": "fleet-result",
                    "result": "BLOCKED",
                    "reason_code": "post-pass-mutation",
                },
            )
            return terminal_block(
                "A task that already passed was modified after validation."
            )
        incomplete = incomplete_tasks(contract, state)
        if forced:
            active = state.get("active_subagent")
            validation_in_flight = any(
                state.get("tasks", {})
                .get(task_id, {})
                .get("deterministic_validation")
                == "IN_FLIGHT"
                for task_id in incomplete
            )
            if isinstance(active, dict) or validation_in_flight:
                # Copilot CLI 1.0.82 can deliver a forced root agentStop while
                # a synchronous subagent continuation is still repairing or
                # while its trusted validation vectors are running. That
                # lifecycle event is not a terminal verdict. Marking every
                # incomplete task BLOCKED here races the worker's final stop;
                # a later successful validation then sees a concurrent
                # terminal status and can never recover. Let the active
                # subagent/validation finish and own the task verdict.
                state["consecutive_blocks"] = 0
                save_state(contract, state)
                record_evidence(
                    contract,
                    {
                        "event": "agent-stop-deferred",
                        "result": "STARTED",
                        "reason_code": (
                            "active-subagent"
                            if isinstance(active, dict)
                            else "validation-in-flight"
                        ),
                    },
                )
                return {"decision": "allow"}
            # The turn was already forced to continue by a stop hook. Another
            # `block` is discarded and only walks toward the runaway guard, so
            # self-limit here and end with terminal markers instead of looping.
            markers = []
            for task_id in incomplete:
                task_status(state, task_id)["terminal_status"] = "BLOCKED"
                markers.append(f"FLEET_RESULT: {task_id}: BLOCKED")
            state["consecutive_blocks"] = 0
            save_state(contract, state)
            record_evidence(
                contract,
                {
                    "event": "fleet-result",
                    "result": (
                        "BLOCKED" if incomplete
                        else aggregate_status(contract, state)
                    ),
                    "reason_code": "stop-hook-active",
                },
            )
            if not incomplete:
                return {"decision": "allow"}
            return {
                "decision": "allow",
                "modifiedResponse": "\n".join(
                    ["FLEET_RUN: BLOCKED", *markers,
                     "The stop-hook continuation limit was reached."]
                ),
            }
        if incomplete:
            return block(
                contract,
                state,
                "Fleet work is incomplete for: "
                + ", ".join(incomplete)
                + ". Continue within the configured validation-loop budget; if "
                "it is exhausted, mark the task FAIL or BLOCKED.",
            )
        state["consecutive_blocks"] = 0
        save_state(contract, state)
    status = aggregate_status(contract, state)
    record_evidence(contract, {"event": "fleet-result", "result": status})
    return {"decision": "allow"}


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


HANDLERS = {
    "session-start": handle_session_start,
    "pre-tool-use": handle_pre_tool_use,
    "post-tool-use": handle_post_tool_use,
    "post-tool-use-failure": handle_post_tool_use_failure,
    "subagent-start": handle_subagent_start,
    "subagent-stop": handle_subagent_stop,
    "agent-stop": handle_agent_stop,
    "session-end": handle_session_end,
    "permission-request": handle_permission_request,
    "mcp-tool-call": handle_mcp_tool_call,
}
DENY_EVENTS = {"pre-tool-use", "mcp-tool-call"}
PERMISSION_EVENTS = {"permission-request"}
STOP_EVENTS = {"subagent-stop", "agent-stop"}


def dispatch(
    event: str, payload: dict[str, Any], contract: dict[str, Any]
) -> dict[str, Any]:
    try:
        handler = HANDLERS[event]
    except KeyError as exc:
        raise ValueError(f"unknown fleet hook event: {event}") from exc
    return handler(payload, contract)


def failure_result(event: str, exc: Exception) -> dict[str, Any]:
    """Fail closed without ever emitting an unbounded block loop."""
    label = type(exc).__name__
    if event in DENY_EVENTS:
        return deny(f"fleet hook could not validate the tool request: {label}")
    if event in PERMISSION_EVENTS:
        return {
            "behavior": "deny",
            "message": f"fleet hook could not validate the request: {label}",
        }
    if event in STOP_EVENTS:
        # A corrupt or tampered control plane must yield one bounded terminal
        # decision, never an endless `block` sequence into the runaway guard.
        return terminal_block(
            f"The fleet control plane is not trustworthy ({label}). Stop and "
            "report the blocker; the launcher decides the run verdict."
        )
    if event == "post-tool-use-failure":
        return {
            "additionalContext": (
                "Fleet hook could not retain sealed failure evidence; do not "
                "claim task completion."
            )
        }
    return {}


def main(argv: list[str] | None = None) -> int:
    arguments = sys.argv[1:] if argv is None else argv
    if len(arguments) != 1:
        print("fleet_gate.py requires exactly one event", file=sys.stderr)
        return 2
    event = arguments[0]
    try:
        payload = json.load(sys.stdin)
        if not isinstance(payload, dict):
            raise ValueError("hook payload must be an object")
        contract = load_contract()
        result = {} if contract is None else dispatch(event, payload, contract)
    except Exception as exc:  # noqa: BLE001 - every failure must fail closed
        result = failure_result(event, exc)
    if event == "post-tool-use-failure" and "additionalContext" in result:
        # `postToolUseFailure` command hooks surface guidance through exit 2
        # with the raw stdout appended to the failure the agent sees; an
        # exit-0 JSON body is not applied for this event.
        sys.stdout.write(str(result["additionalContext"]) + "\n")
        return 2
    json.dump(result, sys.stdout, separators=(",", ":"))
    sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
