#!/usr/bin/env python3
"""Sandboxed disposable-worktree executor for trusted fleet validation.

Both the hook handler (`fleet_gate.py`) and the launcher (`run_fleet.py`) must
execute declared validation vectors *without* ever running agent-authored code
as the launching user. This module is the only place either side is allowed to
start a validation process, and it enforces three properties together:

1. **Disposable worktree.** Every vector runs inside a fresh
   `git worktree add --detach <base_head>` checkout. Repository-relative layout
   is preserved, so pytest keeps its `rootdir`, its `conftest.py` discovery and
   its `sys.path` insertion; only the candidate owned paths are overlaid on top
   of the base revision, so a file no task owns can never influence a verdict.
2. **Probed OS sandbox.** The validation child is wrapped in a Seatbelt profile
   (`sandbox-exec`, macOS) or a `bwrap` container (Linux). The backend is
   *probed* before use: it must demonstrably allow a write inside the workspace,
   deny a write outside it, and deny a loopback connection. If no backend can be
   proven, execution raises `SandboxUnavailable` and the caller fails closed.
   There is deliberately no unsandboxed fallback.
3. **Secret-free environment.** The child receives a dedicated minimal
   environment that is built from scratch rather than filtered. The run key, the
   contract path, GitHub/Copilot authentication, and every cloud credential are
   absent by construction, and `assert_no_secrets` re-checks that before exec.

Security notes
--------------
Reads of the repository itself stay permitted because the worktree's `.git`
pointer resolves into the original repository and git would otherwise fail.
Writes outside the disposable workspace are denied by default, and reads of the
control plane and of the launching user's credential directories are denied
explicitly.
"""

from __future__ import annotations

# Importing a sibling module must not leave `__pycache__` inside the hook
# surface; the repository treats generated bytecode there as residue
# (tests/test_fleet_hooks.py::ProcessContractTests). `fleet_gate.py`,
# `run_fleet.py`, and `verify-hooks-loaded.py` all set this before importing
# `fleet_policy`; this module was the one entry point that did not, so running
# it as a script wrote `fleet_policy.cpython-*.pyc` into `.github/hooks/scripts`.
import sys

sys.dont_write_bytecode = True

import json  # noqa: E402
import os  # noqa: E402
import platform  # noqa: E402
import shutil  # noqa: E402
import socket  # noqa: E402
import stat  # noqa: E402
import subprocess  # noqa: E402
import tempfile  # noqa: E402
from contextlib import closing, contextmanager  # noqa: E402
from pathlib import Path  # noqa: E402
from typing import Any, Iterable, Iterator, Mapping, Sequence  # noqa: E402

sys.path.insert(0, str(Path(__file__).resolve().parent))

import fleet_policy  # noqa: E402


BACKEND_SEATBELT = "seatbelt"
BACKEND_BWRAP = "bwrap"
BACKEND_NONE = "none"

WORKSPACE_PREFIX = "ohfleet-validate-"
PROBE_PREFIX = "ohfleet-probe-"
PROBE_TIMEOUT_SECONDS = 60
WORKTREE_TIMEOUT_SECONDS = 300

# Repository subtrees that are never overlaid onto the disposable worktree.
# `.github/hooks` carries the trusted handler itself, `.test-results` is the
# untrusted artifact directory, and `.git` is the repository's own metadata.
OVERLAY_DENIED_PREFIXES = (".git", ".github/hooks", ".test-results")

# Directories under the launching user's home that must not be readable by a
# validation child even though general reads are permitted.
CREDENTIAL_DIRECTORY_NAMES = (
    ".aws",
    ".azure",
    ".config/gcloud",
    ".config/gh",
    ".copilot",
    ".docker",
    ".gnupg",
    ".kube",
    ".ssh",
)
CREDENTIAL_FILE_NAMES = (
    ".git-credentials",
    ".netrc",
    ".npmrc",
    ".pypirc",
)

# Environment names that must never reach a validation child. Checked by name,
# by prefix, and by the shared sensitive-name pattern.
VALIDATION_DENIED_ENVIRONMENT_NAMES = frozenset(
    {
        fleet_policy.KEY_ENV,
        fleet_policy.CONTRACT_ENV,
        "GH_TOKEN",
        "GITHUB_TOKEN",
        "GH_ENTERPRISE_TOKEN",
        "GITHUB_ENTERPRISE_TOKEN",
        "KUBECONFIG",
    }
)
VALIDATION_DENIED_ENVIRONMENT_PREFIXES = (
    "ARM_",
    "AWS_",
    "AZURE_",
    "COPILOT_",
    "GCP_",
    "GH_",
    "GITHUB_",
    "GOOGLE_",
    "KUBE_",
    "NPM_",
    "OPEN_HORIZONS_",
    "TF_",
)
# The only ambient names copied into the validation environment. Everything
# else is constructed, so a new secret variable cannot appear by omission.
VALIDATION_INHERITED_ENVIRONMENT_NAMES = (
    "LANG",
    "LC_ALL",
    "LC_CTYPE",
    "PATH",
    "TZ",
)


class SandboxUnavailable(RuntimeError):
    """No sandbox backend could be proven on this host."""


class WorktreeError(RuntimeError):
    """The disposable validation worktree could not be prepared."""


class EnvironmentLeak(RuntimeError):
    """A validation child environment carried a forbidden variable."""


# ---------------------------------------------------------------------------
# Validation child environment
# ---------------------------------------------------------------------------


def assert_no_secrets(environment: Mapping[str, str]) -> None:
    """Raise when a validation environment carries a forbidden variable.

    This is a hard assertion, not a filter: the environment is built from a
    fixed list, so a hit here means a caller mutated it and the run must fail
    closed rather than execute with the run key or a token in scope.
    """
    for name in sorted(environment):
        if name in VALIDATION_DENIED_ENVIRONMENT_NAMES:
            raise EnvironmentLeak(f"validation environment carries {name}")
        if name.startswith(VALIDATION_DENIED_ENVIRONMENT_PREFIXES):
            raise EnvironmentLeak(f"validation environment carries {name}")
        if fleet_policy.ENVIRONMENT_SENSITIVE.search(name):
            raise EnvironmentLeak(f"validation environment carries {name}")


def validation_environment(
    workspace_home: Path,
    workspace_tmp: Path,
    *,
    source: Mapping[str, str] | None = None,
) -> dict[str, str]:
    """Build the dedicated, minimal environment for a validation child.

    Distinct from `fleet_policy.scrub_environment()`, which builds the *Copilot*
    child environment and legitimately carries authentication. Nothing here can
    locate the control directory: `HOME` and `TMPDIR` both point inside the
    disposable workspace.
    """
    origin = os.environ if source is None else source
    environment: dict[str, str] = {
        "HOME": str(workspace_home),
        "TMPDIR": str(workspace_tmp),
        "TEMP": str(workspace_tmp),
        "TMP": str(workspace_tmp),
        "PYTHONDONTWRITEBYTECODE": "1",
        "PYTHONHASHSEED": "0",
        "PYTHONUNBUFFERED": "1",
        "GIT_OPTIONAL_LOCKS": "0",
        "GIT_TERMINAL_PROMPT": "0",
        "GIT_CONFIG_NOSYSTEM": "1",
        "NO_COLOR": "1",
        "CI": "1",
    }
    for name in VALIDATION_INHERITED_ENVIRONMENT_NAMES:
        value = origin.get(name)
        if isinstance(value, str) and value:
            environment[name] = value
    environment.setdefault("PATH", os.defpath)
    assert_no_secrets(environment)
    return environment


# ---------------------------------------------------------------------------
# Sandbox profiles
# ---------------------------------------------------------------------------


def _quote(value: Path | str) -> str:
    text = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{text}"'


def credential_paths(home: Path | None = None) -> list[Path]:
    """Return the launching user's credential locations that must be unreadable."""
    base = Path(os.environ.get("HOME", str(Path.home()))) if home is None else home
    paths: list[Path] = []
    for name in (*CREDENTIAL_DIRECTORY_NAMES, *CREDENTIAL_FILE_NAMES):
        candidate = base / name
        if candidate.exists() or candidate.is_symlink():
            paths.append(candidate)
    return paths


def seatbelt_profile(
    writable: Sequence[Path],
    denied_reads: Sequence[Path],
    *,
    allow_network: bool = False,
) -> str:
    """Render a Seatbelt profile that is default-deny for writes.

    Seatbelt evaluates every rule and the *last* match wins, so the ordering
    below is load-bearing: `(deny default)` first, the broad read allowance and
    the narrow write allowances next, and the explicit read denials last.
    """
    lines = [
        "(version 1)",
        "(deny default)",
        "(allow process-exec*)",
        "(allow process-fork)",
        "(allow sysctl-read)",
        "(allow signal (target self))",
        "(allow file-read*)",
        "(allow mach-lookup)",
        "(allow ipc-posix-shm)",
    ]
    if writable:
        subpaths = " ".join(f"(subpath {_quote(path)})" for path in writable)
        lines.append(f"(allow file-write* {subpaths})")
    devices = " ".join(
        f"(literal {_quote(device)})"
        for device in (
            "/dev/null",
            "/dev/zero",
            "/dev/random",
            "/dev/urandom",
            "/dev/dtracehelper",
            "/dev/tty",
            "/dev/stdout",
            "/dev/stderr",
        )
    )
    lines.append(f"(allow file-write-data {devices})")
    lines.append(
        "(allow file-ioctl (literal \"/dev/dtracehelper\") "
        "(literal \"/dev/null\") (literal \"/dev/tty\"))"
    )
    if denied_reads:
        denied = " ".join(f"(subpath {_quote(path)})" for path in denied_reads)
        lines.append(f"(deny file-read* {denied})")
        lines.append(f"(deny file-write* {denied})")
    lines.append("(allow network*)" if allow_network else "(deny network*)")
    return "\n".join(lines) + "\n"


def bwrap_command(
    argv: Sequence[str],
    *,
    writable: Sequence[Path],
    denied_reads: Sequence[Path],
    workdir: Path,
    allow_network: bool = False,
) -> list[str]:
    """Render a `bwrap` invocation with a read-only root and narrow writes."""
    command = [
        "bwrap",
        "--ro-bind",
        "/",
        "/",
        "--dev",
        "/dev",
        "--proc",
        "/proc",
        "--tmpfs",
        "/tmp",
    ]
    for path in denied_reads:
        if path.is_dir():
            command.extend(["--tmpfs", str(path)])
        else:
            command.extend(["--ro-bind", "/dev/null", str(path)])
    for path in writable:
        command.extend(["--bind", str(path), str(path)])
    if not allow_network:
        command.append("--unshare-net")
    command.extend(
        [
            "--unshare-pid",
            "--unshare-ipc",
            "--unshare-uts",
            "--die-with-parent",
            "--new-session",
            "--chdir",
            str(workdir),
            "--",
            *argv,
        ]
    )
    return command


# ---------------------------------------------------------------------------
# Backend detection and enforcement probe
# ---------------------------------------------------------------------------


PROBE_SCRIPT = '''
import json, os, socket, sys

result = {}
try:
    with open(os.environ["OHPROBE_ALLOWED"], "w", encoding="utf-8") as handle:
        handle.write("ok")
    result["allowed_write"] = True
except OSError:
    result["allowed_write"] = False
try:
    with open(os.environ["OHPROBE_FORBIDDEN"], "w", encoding="utf-8") as handle:
        handle.write("pwned")
    result["forbidden_write"] = True
except OSError:
    result["forbidden_write"] = False
port = int(os.environ.get("OHPROBE_PORT", "0"))
if port:
    connection = socket.socket()
    connection.settimeout(2)
    try:
        connection.connect(("127.0.0.1", port))
        result["network"] = True
    except OSError:
        result["network"] = False
    finally:
        connection.close()
else:
    result["network"] = None
sys.stdout.write(json.dumps(result))
'''


def available_backend() -> str:
    """Return the backend this host could support, without probing it."""
    system = platform.system()
    if system == "Darwin" and shutil.which("sandbox-exec"):
        return BACKEND_SEATBELT
    if system == "Linux" and shutil.which("bwrap"):
        return BACKEND_BWRAP
    return BACKEND_NONE


def _real(path: Path) -> Path:
    """Resolve symlinks; Seatbelt matches real paths, not `/tmp` aliases."""
    return Path(os.path.realpath(str(path)))


# Fallback workspace parents, in preference order, for hosts whose `TMPDIR`
# cannot be used. Both are POSIX-standard world-writable temporary roots.
NEUTRAL_TEMPORARY_BASES = ("/tmp", "/var/tmp")


def neutral_temporary_base(
    repository_root: Path | None = None,
    control_directory: Path | None = None,
) -> Path:
    """Return a workspace parent outside the repository and the control plane.

    The launcher points the Copilot child's `TMPDIR` at the control-plane
    scratch directory, and every hook process inherits it. Honouring `TMPDIR`
    here would create the disposable worktree *inside* the directory the
    sandbox profile denies reads of, so the validation child could not read its
    own checkout — a silent, confusing `Operation not permitted` rather than a
    security property. The workspace must also never land inside the
    repository, where a stray worktree would corrupt git's own state.
    """
    excluded: list[Path] = []
    for candidate in (repository_root, control_directory):
        if candidate is not None:
            excluded.append(_real(candidate))
    for raw in (tempfile.gettempdir(), *NEUTRAL_TEMPORARY_BASES):
        try:
            resolved = _real(Path(raw))
        except OSError:  # pragma: no cover - realpath rarely raises
            continue
        if not resolved.is_dir() or not os.access(resolved, os.W_OK):
            continue
        if any(fleet_policy.path_is_within(resolved, parent) for parent in excluded):
            continue
        return resolved
    raise SandboxUnavailable(
        "no temporary directory outside the repository and the control plane "
        "is available for a validation workspace"
    )


def wrap_command(
    backend: str,
    argv: Sequence[str],
    *,
    writable: Sequence[Path],
    denied_reads: Sequence[Path],
    workdir: Path,
    profile_path: Path | None = None,
    allow_network: bool = False,
) -> list[str]:
    if backend == BACKEND_SEATBELT:
        if profile_path is None:
            raise SandboxUnavailable("seatbelt backend requires a profile file")
        return ["sandbox-exec", "-f", str(profile_path), *argv]
    if backend == BACKEND_BWRAP:
        return bwrap_command(
            argv,
            writable=writable,
            denied_reads=denied_reads,
            workdir=workdir,
            allow_network=allow_network,
        )
    raise SandboxUnavailable(f"unsupported sandbox backend: {backend}")


@contextmanager
def _loopback_listener() -> Iterator[int]:
    """Bind a local listener so the probe can prove network denial."""
    server = socket.socket()
    try:
        server.bind(("127.0.0.1", 0))
        server.listen(1)
    except OSError:
        server.close()
        yield 0
        return
    with closing(server):
        yield int(server.getsockname()[1])


def probe_backend(backend: str) -> dict[str, Any]:
    """Prove the backend enforces containment, or raise `SandboxUnavailable`.

    A silently-ignored wrapper is exactly the failure mode this exists to catch,
    so the probe asserts a *positive* control (a write inside the workspace
    succeeds) and two *negative* controls (a write outside it and a loopback
    connection both fail).
    """
    if backend == BACKEND_NONE:
        raise SandboxUnavailable(
            "no validation sandbox backend is available on this host"
        )
    workspace = Path(tempfile.mkdtemp(prefix=PROBE_PREFIX, dir=neutral_temporary_base()))
    forbidden = Path(
        tempfile.mkdtemp(
            prefix=PROBE_PREFIX + "denied-", dir=neutral_temporary_base()
        )
    )
    try:
        real_workspace = _real(workspace)
        real_forbidden = _real(forbidden)
        script = workspace / "probe.py"
        script.write_text(PROBE_SCRIPT, encoding="utf-8")
        profile_path = workspace / "profile.sb"
        if backend == BACKEND_SEATBELT:
            profile_path.write_text(
                seatbelt_profile([real_workspace], []), encoding="utf-8"
            )
        with _loopback_listener() as port:
            environment = {
                "PATH": os.environ.get("PATH", os.defpath),
                "HOME": str(workspace),
                "TMPDIR": str(workspace),
                "PYTHONDONTWRITEBYTECODE": "1",
                "OHPROBE_ALLOWED": str(real_workspace / "ok.txt"),
                "OHPROBE_FORBIDDEN": str(real_forbidden / "pwned.txt"),
                "OHPROBE_PORT": str(port),
            }
            command = wrap_command(
                backend,
                [sys.executable, str(script)],
                writable=[real_workspace],
                denied_reads=[],
                workdir=real_workspace,
                profile_path=profile_path,
                allow_network=False,
            )
            try:
                completed = subprocess.run(
                    command,
                    cwd=str(real_workspace),
                    env=environment,
                    stdout=subprocess.PIPE,
                    stderr=subprocess.PIPE,
                    timeout=PROBE_TIMEOUT_SECONDS,
                    check=False,
                )
            except (OSError, subprocess.TimeoutExpired) as exc:
                raise SandboxUnavailable(
                    f"sandbox backend {backend} could not run the probe: {exc}"
                ) from exc
        if completed.returncode != 0:
            raise SandboxUnavailable(
                f"sandbox backend {backend} probe exited {completed.returncode}"
            )
        try:
            outcome = json.loads(completed.stdout.decode("utf-8", "replace"))
        except json.JSONDecodeError as exc:
            raise SandboxUnavailable(
                f"sandbox backend {backend} probe produced no verdict"
            ) from exc
        if outcome.get("allowed_write") is not True:
            raise SandboxUnavailable(
                f"sandbox backend {backend} blocked its own workspace write"
            )
        if outcome.get("forbidden_write") is not False:
            raise SandboxUnavailable(
                f"sandbox backend {backend} did not deny an outside write"
            )
        if (real_forbidden / "pwned.txt").exists():
            raise SandboxUnavailable(
                f"sandbox backend {backend} allowed an outside write to land"
            )
        if outcome.get("network") is True:
            raise SandboxUnavailable(
                f"sandbox backend {backend} did not deny a loopback connection"
            )
        return {
            "backend": backend,
            "write_denied": True,
            "network_denied": outcome.get("network") is False,
        }
    finally:
        shutil.rmtree(workspace, ignore_errors=True)
        shutil.rmtree(forbidden, ignore_errors=True)


_PROBE_CACHE: dict[str, dict[str, Any]] = {}


def proven_backend(*, backend: str | None = None) -> dict[str, Any]:
    """Return a probed backend descriptor, or raise `SandboxUnavailable`.

    The probe result is cached for the lifetime of the process. Hook handlers
    are one process per event, so this is at most one probe per validation.
    """
    selected = available_backend() if backend is None else backend
    cached = _PROBE_CACHE.get(selected)
    if cached is not None:
        return cached
    proven = probe_backend(selected)
    _PROBE_CACHE[selected] = proven
    return proven


def reset_probe_cache() -> None:
    _PROBE_CACHE.clear()


# ---------------------------------------------------------------------------
# Disposable worktree
# ---------------------------------------------------------------------------


def _git(root: Path, *arguments: str, timeout: int = WORKTREE_TIMEOUT_SECONDS):
    return subprocess.run(
        ["git", *arguments],
        cwd=str(root),
        text=True,
        capture_output=True,
        check=False,
        timeout=timeout,
        env={
            **fleet_policy.scrub_environment(),
            "GIT_OPTIONAL_LOCKS": "0",
            "GIT_TERMINAL_PROMPT": "0",
        },
    )


def overlay_denied(relative: str) -> bool:
    for prefix in OVERLAY_DENIED_PREFIXES:
        if relative == prefix or relative.startswith(f"{prefix}/"):
            return True
    return any(part in fleet_policy.DIGEST_EXCLUDED_NAMES for part in Path(relative).parts)


def _remove(path: Path) -> None:
    if path.is_symlink() or path.is_file():
        path.unlink()
    elif path.is_dir():
        shutil.rmtree(path)


def _copy_symlink(source: Path, destination: Path, source_root: Path) -> bool:
    """Copy a symlink only when its target stays inside the repository."""
    target = os.readlink(source)
    resolved = (source.parent / target).resolve()
    if not fleet_policy.path_is_within(resolved, source_root):
        return False
    destination.parent.mkdir(parents=True, exist_ok=True)
    os.symlink(target, destination)
    return True


def _copy_tree(
    source: Path, destination: Path, source_root: Path, skipped: list[str]
) -> None:
    destination.mkdir(parents=True, exist_ok=True)
    for child in sorted(source.iterdir(), key=lambda item: item.name):
        if child.name in fleet_policy.DIGEST_EXCLUDED_NAMES:
            continue
        relative = child.relative_to(source_root).as_posix()
        if overlay_denied(relative):
            skipped.append(relative)
            continue
        target = destination / child.name
        if child.is_symlink():
            if not _copy_symlink(child, target, source_root):
                skipped.append(relative)
            continue
        if child.is_dir():
            _copy_tree(child, target, source_root, skipped)
            continue
        if child.is_file():
            shutil.copy2(child, target)


def overlay_candidate_paths(
    source_root: Path, worktree: Path, relative_paths: Iterable[str]
) -> tuple[list[str], list[str]]:
    """Overlay candidate owned paths from the live tree onto the worktree.

    Returns `(applied, skipped)`. A path that no longer exists in the live tree
    is *removed* from the worktree, so a deletion is reproduced faithfully.
    Control artifacts and symlinks that escape the repository are never copied.
    """
    source_root = source_root.resolve()
    worktree = worktree.resolve()
    applied: list[str] = []
    skipped: list[str] = []
    for raw in sorted({fleet_policy.normalize_relative(str(item)) for item in relative_paths}):
        if not raw or raw == ".":
            skipped.append(raw or ".")
            continue
        if ".." in Path(raw).parts or Path(raw).is_absolute():
            skipped.append(raw)
            continue
        if overlay_denied(raw):
            skipped.append(raw)
            continue
        destination = worktree / raw
        if not fleet_policy.path_is_within(
            Path(os.path.normpath(str(destination))), worktree
        ):
            skipped.append(raw)
            continue
        source = source_root / raw
        _remove(destination)
        if not source.exists() and not source.is_symlink():
            applied.append(raw)
            continue
        if source.is_symlink():
            if _copy_symlink(source, destination, source_root):
                applied.append(raw)
            else:
                skipped.append(raw)
            continue
        if source.is_dir():
            _copy_tree(source, destination, source_root, skipped)
            applied.append(raw)
            continue
        destination.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source, destination)
        applied.append(raw)
    return applied, skipped


def _force_remove_tree(path: Path) -> None:
    def _on_error(function: Any, name: str, _exc: Any) -> None:
        try:
            os.chmod(name, stat.S_IWUSR | stat.S_IRUSR | stat.S_IXUSR)
            function(name)
        except OSError:
            pass

    shutil.rmtree(path, onerror=_on_error)


class ValidationWorkspace:
    """A disposable, sandboxed execution workspace for validation vectors.

    Layout (all outside both the repository and the control directory, so the
    child cannot locate the control plane from `HOME`, `TMPDIR`, or `cwd`):

        <workspace>/repo/   the detached `base_head` worktree, overlaid
        <workspace>/tmp/    the child's `TMPDIR`
        <workspace>/home/   the child's `HOME`
        <workspace>/profile.sb  the generated Seatbelt profile
    """

    def __init__(
        self,
        repository_root: Path,
        base_head: str,
        *,
        overlay: Sequence[str] = (),
        control_directory: Path | None = None,
        allow_network: bool = False,
        backend: str | None = None,
    ) -> None:
        self.repository_root = repository_root.resolve()
        self.base_head = base_head
        self.overlay = list(overlay)
        self.control_directory = (
            control_directory.resolve() if control_directory is not None else None
        )
        self.allow_network = allow_network
        self._requested_backend = backend
        self.backend: str = BACKEND_NONE
        self.sandbox: dict[str, Any] = {}
        self.applied: list[str] = []
        self.skipped: list[str] = []
        self.root: Path | None = None
        self.worktree: Path | None = None

    # -- lifecycle ---------------------------------------------------------

    def __enter__(self) -> "ValidationWorkspace":
        self.sandbox = proven_backend(backend=self._requested_backend)
        self.backend = str(self.sandbox["backend"])
        self.root = Path(
            tempfile.mkdtemp(
                prefix=WORKSPACE_PREFIX,
                dir=neutral_temporary_base(
                    self.repository_root, self.control_directory
                ),
            )
        )
        os.chmod(self.root, fleet_policy.CONTROL_DIRECTORY_MODE)
        try:
            self.worktree = self.root / "repo"
            (self.root / "tmp").mkdir()
            (self.root / "home").mkdir()
            self._create_worktree()
            self.applied, self.skipped = overlay_candidate_paths(
                self.repository_root, self.worktree, self.overlay
            )
            self._write_profile()
        except BaseException:
            self.close()
            raise
        return self

    def __exit__(self, *_exception: Any) -> None:
        self.close()

    def close(self) -> None:
        root = self.root
        self.root = None
        if root is None:
            return
        _force_remove_tree(root)
        _git(self.repository_root, "worktree", "prune")

    # -- construction ------------------------------------------------------

    def _create_worktree(self) -> None:
        assert self.worktree is not None
        if not self.base_head:
            raise WorktreeError("contract carries no base_head to validate against")
        try:
            result = _git(
                self.repository_root,
                "worktree",
                "add",
                "--detach",
                "--no-checkout",
                str(self.worktree),
                self.base_head,
            )
        except (OSError, subprocess.TimeoutExpired) as exc:
            raise WorktreeError(f"cannot create the validation worktree: {exc}") from exc
        if result.returncode != 0:
            raise WorktreeError(
                "cannot create the validation worktree: "
                + (result.stderr.strip().splitlines() or ["git failed"])[-1]
            )
        checkout = _git(self.worktree, "checkout", "--detach", self.base_head)
        if checkout.returncode != 0:
            raise WorktreeError(
                "cannot check out the validation worktree: "
                + (checkout.stderr.strip().splitlines() or ["git failed"])[-1]
            )

    def _denied_reads(self) -> list[Path]:
        denied: list[Path] = []
        if self.control_directory is not None:
            denied.append(_real(self.control_directory))
        denied.extend(_real(path) for path in credential_paths())
        return denied

    def _writable(self) -> list[Path]:
        assert self.root is not None
        return [_real(self.root)]

    def _write_profile(self) -> None:
        assert self.root is not None
        if self.backend != BACKEND_SEATBELT:
            return
        (self.root / "profile.sb").write_text(
            seatbelt_profile(
                self._writable(),
                self._denied_reads(),
                allow_network=self.allow_network,
            ),
            encoding="utf-8",
        )

    # -- execution ---------------------------------------------------------

    def environment(self) -> dict[str, str]:
        assert self.root is not None
        return validation_environment(self.root / "home", self.root / "tmp")

    def run(
        self, argv: Sequence[str], *, timeout: float
    ) -> subprocess.CompletedProcess[bytes]:
        """Run one repository-relative argv inside the sandboxed worktree."""
        if self.root is None or self.worktree is None:
            raise SandboxUnavailable("validation workspace is closed")
        environment = self.environment()
        assert_no_secrets(environment)
        command = wrap_command(
            self.backend,
            list(argv),
            writable=self._writable(),
            denied_reads=self._denied_reads(),
            workdir=_real(self.worktree),
            profile_path=self.root / "profile.sb",
            allow_network=self.allow_network,
        )
        return subprocess.run(
            command,
            cwd=str(self.worktree),
            env=environment,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            timeout=timeout,
            check=False,
            start_new_session=True,
        )


def describe_backend() -> str:
    """Return a short backend label for evidence records."""
    return available_backend()
